// Static fallback inventories (deterministic; used when no live
// checkout or materialized node folders are available).
//
// GENERATED — do not hand-edit. Regenerate with
// `crates/common/connect/scripts/regen_static_catalog.py` (see CATALOG.md).
// Sources:
// - n8n nodes-base (442 classes) + @n8n/nodes-langchain (122 classes)
//   from `packages/{nodes-base,@n8n/nodes-langchain}/dist/known/nodes.json`
//   of the 2026-08-21 n8n checkout used for discovery.
// - flow-like (1845 `impl NodeLogic for X` nodes across 11 catalog
//   families) extracted with the same marker scan as
//   `collect_flow_logic`, from Rheosoph/flow-like @ 1545749d.

const N8N_BASE_NODES: &[&str] = &[
    "ActionNetwork",
    "ActiveCampaign",
    "ActiveCampaignTrigger",
    "AcuitySchedulingTrigger",
    "Adalo",
    "Affinity",
    "AffinityTrigger",
    "AgileCrm",
    "Airtable",
    "AirtableTrigger",
    "Airtop",
    "AiTransform",
    "Amqp",
    "AmqpTrigger",
    "ApiTemplateIo",
    "Asana",
    "AsanaTrigger",
    "Autopilot",
    "AutopilotTrigger",
    "AwsLambda",
    "AwsSns",
    "AwsSnsTrigger",
    "AwsCertificateManager",
    "AwsCognito",
    "AwsComprehend",
    "AwsDynamoDB",
    "AwsElb",
    "AwsIam",
    "AwsRekognition",
    "AwsS3",
    "AwsSes",
    "AwsSqs",
    "AwsTextract",
    "AwsTranscribe",
    "BambooHr",
    "Bannerbear",
    "Baserow",
    "Beeminder",
    "BitbucketTrigger",
    "Bitly",
    "Bitwarden",
    "Box",
    "BoxTrigger",
    "Brandfetch",
    "Bubble",
    "CalTrigger",
    "CalendlyTrigger",
    "Chargebee",
    "ChargebeeTrigger",
    "CircleCi",
    "CiscoWebex",
    "CiscoWebexTrigger",
    "Cloudflare",
    "Clearbit",
    "ClickUp",
    "ClickUpTrigger",
    "Clockify",
    "ClockifyTrigger",
    "Cockpit",
    "Coda",
    "Code",
    "CoinGecko",
    "CompareDatasets",
    "Compression",
    "Confluence",
    "Contentful",
    "ConvertKit",
    "ConvertKitTrigger",
    "Copper",
    "CopperTrigger",
    "Cortex",
    "CrateDb",
    "DynamicCredentialCheck",
    "Cron",
    "Crypto",
    "Currents",
    "CurrentsTrigger",
    "CustomerIo",
    "CustomerIoTrigger",
    "Databricks",
    "DataTable",
    "DateTime",
    "DebugHelper",
    "DeepL",
    "Demio",
    "Dhl",
    "Discord",
    "Discourse",
    "Disqus",
    "Drift",
    "Dropbox",
    "Dropcontact",
    "EditImage",
    "E2eTest",
    "E2eTestPollingTrigger",
    "Egoi",
    "Elasticsearch",
    "ElasticSecurity",
    "EmailReadImap",
    "EmailSend",
    "Emelia",
    "EmeliaTrigger",
    "ERPNext",
    "ErrorTrigger",
    "EvaluationTrigger",
    "Evaluation",
    "EventbriteTrigger",
    "ExecuteCommand",
    "ExecuteWorkflow",
    "ExecuteWorkflowTrigger",
    "ExecutionData",
    "FacebookGraphApi",
    "FacebookTrigger",
    "FacebookLeadAdsTrigger",
    "FigmaTrigger",
    "FileMaker",
    "ReadWriteFile",
    "ConvertToFile",
    "ExtractFromFile",
    "Filter",
    "Flow",
    "FlowTrigger",
    "Form",
    "FormTrigger",
    "FormIoTrigger",
    "FormstackTrigger",
    "Freshdesk",
    "Freshservice",
    "FreshworksCrm",
    "Ftp",
    "Function",
    "FunctionItem",
    "GetResponse",
    "GetResponseTrigger",
    "Ghost",
    "Git",
    "Github",
    "GithubTrigger",
    "Gitlab",
    "GitlabTrigger",
    "Gong",
    "GoogleAds",
    "GoogleAnalytics",
    "GoogleBigQuery",
    "GoogleBooks",
    "GoogleCalendar",
    "GoogleCalendarTrigger",
    "GoogleChat",
    "GoogleCloudNaturalLanguage",
    "GoogleCloudStorage",
    "GoogleContacts",
    "GoogleDocs",
    "GoogleDrive",
    "GoogleDriveTrigger",
    "GoogleFirebaseCloudFirestore",
    "GoogleFirebaseRealtimeDatabase",
    "Gmail",
    "GmailTrigger",
    "GSuiteAdmin",
    "GoogleBusinessProfile",
    "GoogleBusinessProfileTrigger",
    "GooglePerspective",
    "GoogleSheets",
    "GoogleSheetsTrigger",
    "GoogleSlides",
    "GoogleTasks",
    "GoogleTranslate",
    "YouTube",
    "Gotify",
    "GoToWebinar",
    "Grafana",
    "GraphQL",
    "Grist",
    "GumroadTrigger",
    "HackerNews",
    "HaloPSA",
    "Harvest",
    "HelpScout",
    "HelpScoutTrigger",
    "HighLevel",
    "HomeAssistant",
    "HtmlExtract",
    "Html",
    "HttpRequest",
    "Hubspot",
    "HubspotTrigger",
    "HumanticAi",
    "Hunter",
    "ICalendar",
    "If",
    "Intercom",
    "Interval",
    "InvoiceNinja",
    "InvoiceNinjaTrigger",
    "ItemLists",
    "Iterable",
    "Jenkins",
    "JinaAi",
    "Jira",
    "JiraTrigger",
    "JotFormTrigger",
    "Jwt",
    "Kafka",
    "KafkaTrigger",
    "Keap",
    "KeapTrigger",
    "KoBoToolbox",
    "KoBoToolboxTrigger",
    "Ldap",
    "Lemlist",
    "LemlistTrigger",
    "Line",
    "Linear",
    "LinearTrigger",
    "LingvaNex",
    "LinkedIn",
    "LocalFileTrigger",
    "LoneScaleTrigger",
    "LoneScale",
    "Magento2",
    "Mailcheck",
    "Mailchimp",
    "MailchimpTrigger",
    "MailerLite",
    "MailerLiteTrigger",
    "Mailgun",
    "Mailjet",
    "MailjetTrigger",
    "Mandrill",
    "ManualTrigger",
    "Markdown",
    "Marketstack",
    "Matrix",
    "Mattermost",
    "Mautic",
    "MauticTrigger",
    "Medium",
    "Merge",
    "MessageAnAgent",
    "MessageBird",
    "Metabase",
    "AzureCosmosDb",
    "MicrosoftDynamicsCrm",
    "MicrosoftEntra",
    "MicrosoftExcel",
    "MicrosoftExcelSharePoint",
    "MicrosoftGraphSecurity",
    "MicrosoftOneDrive",
    "MicrosoftOneDriveTrigger",
    "MicrosoftOutlook",
    "MicrosoftOutlookTrigger",
    "MicrosoftSharePoint",
    "MicrosoftSql",
    "AzureStorage",
    "MicrosoftTeams",
    "MicrosoftTeamsTrigger",
    "MicrosoftToDo",
    "Mindee",
    "Misp",
    "MistralAi",
    "Mocean",
    "MondayCom",
    "MongoDb",
    "MonicaCrm",
    "MoveBinaryData",
    "Mqtt",
    "MqttTrigger",
    "Msg91",
    "MySql",
    "N8n",
    "N8nTrainingCustomerDatastore",
    "N8nTrainingCustomerMessenger",
    "N8nTrigger",
    "Nasa",
    "Netlify",
    "NetlifyTrigger",
    "NextCloud",
    "NocoDB",
    "Brevo",
    "BrevoTrigger",
    "StickyNote",
    "NoOp",
    "Onfleet",
    "OnfleetTrigger",
    "NetscalerAdc",
    "Notion",
    "NotionTrigger",
    "Npm",
    "Odoo",
    "Okta",
    "OneSimpleApi",
    "OpenAi",
    "OpenThesaurus",
    "OpenWeatherMap",
    "OracleSql",
    "Orbit",
    "Oura",
    "Paddle",
    "PagerDuty",
    "PayPal",
    "PayPalTrigger",
    "Peekalink",
    "Perplexity",
    "Phantombuster",
    "PhilipsHue",
    "Pipedrive",
    "PipedriveTrigger",
    "Plivo",
    "PostBin",
    "Postgres",
    "PostgresTrigger",
    "PostHog",
    "PostmarkTrigger",
    "ProfitWell",
    "Pushbullet",
    "Pushcut",
    "PushcutTrigger",
    "Pushover",
    "QuestDb",
    "QuickBase",
    "QuickBooks",
    "QuickChart",
    "RabbitMQ",
    "RabbitMQTrigger",
    "Raindrop",
    "ReadBinaryFile",
    "ReadBinaryFiles",
    "ReadPDF",
    "Reddit",
    "Redis",
    "RedisTrigger",
    "RenameKeys",
    "RespondToWebhook",
    "Rocketchat",
    "RssFeedRead",
    "RssFeedReadTrigger",
    "Rundeck",
    "S3",
    "Salesforce",
    "SalesforceTrigger",
    "Salesmate",
    "ScheduleTrigger",
    "SeaTable",
    "SeaTableTrigger",
    "SecurityScorecard",
    "Segment",
    "SendGrid",
    "Sendy",
    "SentryIo",
    "ServiceNow",
    "Set",
    "Shopify",
    "ShopifyTrigger",
    "Signl4",
    "Simulate",
    "SimulateTrigger",
    "Slack",
    "SlackTrigger",
    "Sms77",
    "Snowflake",
    "SplitInBatches",
    "Splunk",
    "Spotify",
    "SpreadsheetFile",
    "SseTrigger",
    "Ssh",
    "Stackby",
    "StopAndError",
    "Storyblok",
    "Strapi",
    "Strava",
    "StravaTrigger",
    "Stripe",
    "StripeTrigger",
    "Supabase",
    "SurveyMonkeyTrigger",
    "Switch",
    "SyncroMsp",
    "Taiga",
    "TaigaTrigger",
    "Tapfiliate",
    "Telegram",
    "TelegramTrigger",
    "TheHiveProject",
    "TheHiveProjectTrigger",
    "TheHive",
    "TheHiveTrigger",
    "TimescaleDb",
    "Todoist",
    "TogglTrigger",
    "Totp",
    "TravisCi",
    "Trello",
    "TrelloTrigger",
    "TimeSaved",
    "Twake",
    "Twilio",
    "TwilioTrigger",
    "Twist",
    "Twitter",
    "TypeformTrigger",
    "UnleashedSoftware",
    "Uplead",
    "UProc",
    "UptimeRobot",
    "UrlScanIo",
    "Vero",
    "VenafiTlsProtectCloud",
    "VenafiTlsProtectCloudTrigger",
    "VenafiTlsProtectDatacenter",
    "Vonage",
    "Wait",
    "Webflow",
    "WebflowTrigger",
    "Webhook",
    "Wekan",
    "WhatsAppTrigger",
    "WhatsApp",
    "Wise",
    "WiseTrigger",
    "WooCommerce",
    "WooCommerceTrigger",
    "Wordpress",
    "WorkableTrigger",
    "WorkflowTrigger",
    "WriteBinaryFile",
    "WufooTrigger",
    "Xero",
    "Xml",
    "Yourls",
    "Zammad",
    "Zendesk",
    "ZendeskTrigger",
    "ZohoCrm",
    "Zoom",
    "Zulip",
    "Aggregate",
    "Limit",
    "RemoveDuplicates",
    "SplitOut",
    "Sort",
    "Summarize",
];

const N8N_LANGCHAIN_NODES: &[&str] = &[
    "AlibabaCloud",
    "Anthropic",
    "GoogleGemini",
    "MiniMax",
    "Moonshot",
    "Ollama",
    "OpenAi",
    "MicrosoftAgent365Trigger",
    "Agent",
    "AgentTool",
    "OpenAiAssistant",
    "ChainSummarization",
    "ChainLlm",
    "ChainRetrievalQa",
    "SentimentAnalysis",
    "InformationExtractor",
    "TextClassifier",
    "Code",
    "DocumentDefaultDataLoader",
    "DocumentBinaryInputLoader",
    "DocumentGithubLoader",
    "DocumentJsonInputLoader",
    "EmbeddingsCohere",
    "EmbeddingsAwsBedrock",
    "EmbeddingsAzureOpenAi",
    "EmbeddingsGoogleGemini",
    "EmbeddingsGoogleVertex",
    "EmbeddingsHuggingFaceInference",
    "EmbeddingsMistralCloud",
    "EmbeddingsOpenAi",
    "EmbeddingsLemonade",
    "EmbeddingsOllama",
    "EmbeddingsOracleDb",
    "EmbeddingsNvidia",
    "LmChatAlibabaCloud",
    "LmChatAnthropic",
    "LmChatAzureOpenAi",
    "LmChatAwsBedrock",
    "LmChatCohere",
    "LmChatDeepSeek",
    "LmChatGoogleGemini",
    "LmChatGoogleVertex",
    "LmChatGroq",
    "LmChatMistralCloud",
    "LmChatMinimax",
    "LmChatMoonshot",
    "LmChatLemonade",
    "LmChatNvidia",
    "LmChatOllama",
    "LmChatOpenRouter",
    "LmChatVercelAiGateway",
    "LmChatXAiGrok",
    "LmChatOpenAi",
    "LmOpenAi",
    "LmCohere",
    "LmLemonade",
    "LmOllama",
    "LmOpenHuggingFaceInference",
    "McpClient",
    "McpClientTool",
    "McpRegistryClientTool",
    "McpTrigger",
    "MemoryBufferWindow",
    "MemoryMotorhead",
    "MemoryPostgresChat",
    "MemoryMongoDbChat",
    "MemoryRedisChat",
    "MemoryManager",
    "MemoryChatRetriever",
    "MemoryXata",
    "MemoryZep",
    "OutputParserAutofixing",
    "OutputParserItemList",
    "OutputParserStructured",
    "RerankerCohere",
    "RetrieverContextualCompression",
    "RetrieverVectorStore",
    "RetrieverMultiQuery",
    "RetrieverWorkflow",
    "TextSplitterCharacterTextSplitter",
    "TextSplitterRecursiveCharacterTextSplitter",
    "TextSplitterTokenSplitter",
    "ToolCalculator",
    "ToolCode",
    "ToolHttpRequest",
    "ToolSearXng",
    "ToolSerpApi",
    "ToolThink",
    "ToolVectorStore",
    "ToolWikipedia",
    "ToolWolframAlpha",
    "ToolWorkflow",
    "ManualChatTrigger",
    "ChatTrigger",
    "Chat",
    "VectorStoreAzureAISearch",
    "VectorStoreInMemory",
    "VectorStoreInMemoryInsert",
    "VectorStoreInMemoryLoad",
    "VectorStoreMilvus",
    "VectorStoreMongoDBAtlas",
    "VectorStoreOracleDB",
    "VectorStorePGVector",
    "ChatHubVectorStorePGVector",
    "ChatHubVectorStoreQdrant",
    "VectorStorePinecone",
    "ChatHubVectorStorePinecone",
    "VectorStorePineconeInsert",
    "VectorStorePineconeLoad",
    "VectorStoreRedis",
    "VectorStoreQdrant",
    "VectorStoreSupabase",
    "VectorStoreSupabaseInsert",
    "VectorStoreSupabaseLoad",
    "VectorStoreWeaviate",
    "VectorStoreZep",
    "VectorStoreZepInsert",
    "VectorStoreZepLoad",
    "VectorStoreChromaDB",
    "ToolExecutor",
    "ModelSelector",
    "Guardrails",
];

const FLOW_LIKE_NODES: &[(&str, &str)] = &[
    ("automation", "StartSessionNode"),
    ("automation", "StopSessionNode"),
    ("automation", "BrowserSetBasicAuthNode"),
    ("automation", "BrowserSaveCookiesNode"),
    ("automation", "BrowserLoadCookiesNode"),
    ("automation", "BrowserClearCookiesNode"),
    ("automation", "BrowserScreenshotNode"),
    ("automation", "BrowserScreenshotElementNode"),
    ("automation", "BrowserOpenNode"),
    ("automation", "BrowserCloseNode"),
    ("automation", "BrowserGetTextNode"),
    ("automation", "BrowserGetAttributeNode"),
    ("automation", "BrowserGetHtmlNode"),
    ("automation", "BrowserExecuteJsNode"),
    ("automation", "BrowserUploadFileNode"),
    ("automation", "BrowserUploadMultipleFilesNode"),
    ("automation", "BrowserSetDownloadDirNode"),
    ("automation", "BrowserWaitForDownloadNode"),
    ("automation", "BrowserTriggerDownloadNode"),
    ("automation", "BrowserTypeTextNode"),
    ("automation", "BrowserPressKeyNode"),
    ("automation", "BrowserSelectOptionNode"),
    ("automation", "BrowserClickNode"),
    ("automation", "BrowserDoubleClickNode"),
    ("automation", "BrowserHoverNode"),
    ("automation", "BrowserScrollIntoViewNode"),
    ("automation", "BrowserGotoNode"),
    ("automation", "BrowserBackNode"),
    ("automation", "BrowserForwardNode"),
    ("automation", "BrowserReloadNode"),
    ("automation", "BrowserGetConsoleLogsNode"),
    ("automation", "BrowserClearConsoleLogsNode"),
    ("automation", "BrowserStartNetworkObserverNode"),
    ("automation", "BrowserGetNetworkRequestsNode"),
    ("automation", "BrowserWaitForNetworkIdleNode"),
    ("automation", "BrowserNewPageNode"),
    ("automation", "BrowserClosePageNode"),
    ("automation", "BrowserGetDomSnapshotNode"),
    ("automation", "BrowserGetAccessibilitySnapshotNode"),
    ("automation", "BrowserGetElementSnapshotNode"),
    ("automation", "BrowserGetLocalStorageNode"),
    ("automation", "BrowserSetLocalStorageNode"),
    ("automation", "BrowserGetSessionStorageNode"),
    ("automation", "BrowserSetSessionStorageNode"),
    ("automation", "BrowserClearStorageNode"),
    ("automation", "BrowserGetAllStorageNode"),
    ("automation", "BrowserWaitForNode"),
    ("automation", "BrowserWaitForDelayNode"),
    ("automation", "ComputerGetAccessibilityTreeNode"),
    ("automation", "ComputerFindAccessibilityElementNode"),
    ("automation", "ComputerScreenshotNode"),
    ("automation", "ClipboardGetTextNode"),
    ("automation", "ClipboardSetTextNode"),
    ("automation", "ClipboardGetImageNode"),
    ("automation", "ClipboardSetImageNode"),
    ("automation", "ComputerListDisplaysNode"),
    ("automation", "ComputerGetDisplayNode"),
    ("automation", "ComputerGetPrimaryDisplayNode"),
    ("automation", "ComputerKeyPressNode"),
    ("automation", "ComputerKeyTypeNode"),
    ("automation", "ComputerMouseMoveNode"),
    ("automation", "ComputerNaturalMouseMoveNode"),
    ("automation", "ComputerMouseClickNode"),
    ("automation", "ComputerMouseDoubleClickNode"),
    ("automation", "ComputerMouseDragNode"),
    ("automation", "ComputerScrollNode"),
    ("automation", "ComputerWaitNode"),
    ("automation", "ListWindowsNode"),
    ("automation", "GetActiveWindowNode"),
    ("automation", "FindWindowByTitleNode"),
    ("automation", "LaunchAppNode"),
    ("automation", "CaptureWindowNode"),
    ("automation", "FocusWindowNode"),
    ("automation", "ComputeFingerprintHashNode"),
    ("automation", "ExtractFingerprintDataNode"),
    ("automation", "CreateFingerprintNode"),
    ("automation", "CreateFingerprintFromJsonNode"),
    ("automation", "CreateMatchOptionsNode"),
    ("automation", "CompareFingerprintsNode"),
    ("automation", "MatchFingerprintNode"),
    ("automation", "UpdateFingerprintNode"),
    ("automation", "RecordFingerprintMatchNode"),
    ("automation", "FingerprintToJsonNode"),
    ("automation", "LLMClassifyScreenNode"),
    ("automation", "LLMExtractFromScreenNode"),
    ("automation", "LLMFindElementNode"),
    ("automation", "LLMDiagnoseAndHealNode"),
    ("automation", "LLMHealSelectorNode"),
    ("automation", "LLMHealTemplateNode"),
    ("automation", "LLMObserveScreenNode"),
    ("automation", "LLMDescribeElementNode"),
    ("automation", "LLMSuggestNextStepNode"),
    ("automation", "LLMPlanActionsNode"),
    ("automation", "LLMRankCandidatesNode"),
    ("automation", "LLMResolveElementNode"),
    ("automation", "ClickAtPositionNode"),
    ("automation", "TypeTextNode"),
    ("automation", "DragAndDropNode"),
    ("automation", "ScrollNode"),
    ("automation", "AssertTemplateExistsNode"),
    ("automation", "AssertColorAtPositionNode"),
    ("automation", "SaveCheckpointNode"),
    ("automation", "ParseCheckpointNode"),
    ("automation", "DiagnoseFailureNode"),
    ("automation", "TryCatchNode"),
    ("automation", "ErrorRecoveryNode"),
    ("automation", "LocateByTemplateNode"),
    ("automation", "LocateByColorNode"),
    ("automation", "LogActionNode"),
    ("automation", "StartTimerNode"),
    ("automation", "CalculateElapsedNode"),
    ("automation", "RetryLoopNode"),
    ("automation", "TakeSnapshotNode"),
    ("automation", "WithTimeoutNode"),
    ("automation", "WaitForTemplateNode"),
    ("automation", "WaitForColorNode"),
    ("automation", "DelayNode"),
    ("automation", "BuildSelectorNode"),
    ("automation", "CreateSelectorSetNode"),
    ("automation", "AddToSelectorSetNode"),
    ("automation", "GetPrimarySelectorNode"),
    ("automation", "SelectorToStringNode"),
    ("automation", "RankSelectorsNode"),
    ("automation", "GetBestSelectorNode"),
    ("automation", "ValidateSelectorNode"),
    ("automation", "RankedSetToSelectorSetNode"),
    ("automation", "ClickTemplateNode"),
    ("automation", "FindTemplateNode"),
    ("automation", "FindAllTemplatesNode"),
    ("automation", "ScreenshotToFileNode"),
    ("automation", "ScreenshotRegionNode"),
    ("automation", "GetPixelColorNode"),
    ("automation", "GetScreenSizeNode"),
    ("automation", "WaitTemplateNode"),
    ("automation", "WaitTemplateDisappearNode"),
    ("data", "GetMeNode"),
    ("data", "AtlassianApiTokenProviderNode"),
    ("data", "AtlassianOAuthProviderNode"),
    ("data", "AddConfluenceCommentNode"),
    ("data", "ListConfluenceAttachmentsNode"),
    ("data", "UploadConfluenceAttachmentNode"),
    ("data", "DownloadConfluenceAttachmentNode"),
    ("data", "DeleteConfluenceAttachmentNode"),
    ("data", "GetPageChildrenNode"),
    ("data", "GetPageAncestorsNode"),
    ("data", "CreateConfluencePageNode"),
    ("data", "DeleteConfluencePageNode"),
    ("data", "GetConfluenceCommentsNode"),
    ("data", "GetConfluencePageNode"),
    ("data", "GetLabelsNode"),
    ("data", "AddLabelNode"),
    ("data", "RemoveLabelNode"),
    ("data", "ListConfluenceSpacesNode"),
    ("data", "SearchConfluenceContentNode"),
    ("data", "UpdateConfluencePageNode"),
    ("data", "SearchUsersNode"),
    ("data", "GetCurrentUserNode"),
    ("data", "AddJiraCommentNode"),
    ("data", "GetAttachmentsNode"),
    ("data", "UploadAttachmentNode"),
    ("data", "DownloadAttachmentNode"),
    ("data", "DeleteAttachmentNode"),
    ("data", "GetBoardsNode"),
    ("data", "GetBoardIssuesNode"),
    ("data", "GetBacklogNode"),
    ("data", "CreateJiraIssueNode"),
    ("data", "BatchCreateIssuesNode"),
    ("data", "DeleteJiraIssueNode"),
    ("data", "LinkToEpicNode"),
    ("data", "UnlinkFromEpicNode"),
    ("data", "GetEpicIssuesNode"),
    ("data", "GetFieldsNode"),
    ("data", "SearchFieldsNode"),
    ("data", "GetJiraIssueNode"),
    ("data", "GetProjectIssuesNode"),
    ("data", "GetJiraTransitionsNode"),
    ("data", "GetLinkTypesNode"),
    ("data", "GetIssueLinksNode"),
    ("data", "CreateIssueLinkNode"),
    ("data", "RemoveIssueLinkNode"),
    ("data", "ListJiraProjectsNode"),
    ("data", "SearchJiraIssuesNode"),
    ("data", "GetSprintsNode"),
    ("data", "GetSprintIssuesNode"),
    ("data", "CreateSprintNode"),
    ("data", "UpdateSprintNode"),
    ("data", "MoveToSprintNode"),
    ("data", "TransitionJiraIssueNode"),
    ("data", "UpdateJiraIssueNode"),
    ("data", "GetChangelogNode"),
    ("data", "BatchGetChangelogsNode"),
    ("data", "GetVersionsNode"),
    ("data", "CreateVersionNode"),
    ("data", "BatchCreateVersionsNode"),
    ("data", "UpdateVersionNode"),
    ("data", "GetWorklogNode"),
    ("data", "AddWorklogNode"),
    ("data", "DeleteCacheNode"),
    ("data", "GetOrWriteCacheNode"),
    ("data", "HasCacheNode"),
    ("data", "InvalidateNamespaceNode"),
    ("data", "OpenCacheNode"),
    ("data", "ReadCacheNode"),
    ("data", "WriteCacheNode"),
    ("data", "ListDatabricksClustersNode"),
    ("data", "GetDatabricksClusterNode"),
    ("data", "StartDatabricksClusterNode"),
    ("data", "StopDatabricksClusterNode"),
    ("data", "ListDatabricksDbfsNode"),
    ("data", "ReadDatabricksDbfsNode"),
    ("data", "GetDatabricksDbfsStatusNode"),
    ("data", "ExecuteDatabricksSqlNode"),
    ("data", "ListDatabricksJobsNode"),
    ("data", "RunDatabricksJobNode"),
    ("data", "GetDatabricksJobRunNode"),
    ("data", "CancelDatabricksJobRunNode"),
    ("data", "DatabricksPatProviderNode"),
    ("data", "DatabricksTokenProviderNode"),
    ("data", "DatabricksServicePrincipalProviderNode"),
    ("data", "DatabricksOAuthProviderNode"),
    ("data", "ListDatabricksSqlWarehousesNode"),
    ("data", "StartDatabricksSqlWarehouseNode"),
    ("data", "StopDatabricksSqlWarehouseNode"),
    ("data", "ListDatabricksCatalogsNode"),
    ("data", "ListDatabricksSchemasNode"),
    ("data", "ListDatabricksTablesNode"),
    ("data", "RegisterAthenaNode"),
    ("data", "MountAthenaQueryNode"),
    ("data", "RegisterBigQueryNode"),
    ("data", "RegisterDeltaTableNode"),
    ("data", "DeltaTimeTravelNode"),
    ("data", "DeltaTableInfoNode"),
    ("data", "RegisterHivePartitionedParquetNode"),
    ("data", "RegisterPartitionedJsonNode"),
    ("data", "WriteDeltaTableNode"),
    ("data", "RegisterIcebergTableNode"),
    ("data", "IcebergTableInfoNode"),
    ("data", "IcebergTimeTravelNode"),
    ("data", "RegisterPostgresNode"),
    ("data", "RegisterMysqlNode"),
    ("data", "RegisterSqliteNode"),
    ("data", "RegisterDuckdbNode"),
    ("data", "RegisterClickhouseNode"),
    ("data", "RegisterOracleNode"),
    ("data", "RegisterFlightSqlNode"),
    ("data", "S3StoreNode"),
    ("data", "S3ExpressStoreNode"),
    ("data", "AzureBlobStoreNode"),
    ("data", "GcpStorageStoreNode"),
    ("data", "CloudflareR2StoreNode"),
    ("data", "SmbStoreNode"),
    ("data", "MountStoreParquetNode"),
    ("data", "MountStoreCsvNode"),
    ("data", "MountStoreJsonNode"),
    ("data", "SqlQueryNode"),
    ("data", "CachedSqlQueryNode"),
    ("data", "RegisterExcelNode"),
    ("data", "RegisterLanceTableNode"),
    ("data", "RegisterCSVTableNode"),
    ("data", "CreateDataFusionSessionNode"),
    ("data", "TimeBinAggregationNode"),
    ("data", "DateTruncAggregationNode"),
    ("data", "WindowAggregationNode"),
    ("data", "DateTimeToTimestampNode"),
    ("data", "TimeRangeFilterNode"),
    ("data", "ListTablesNode"),
    ("data", "DescribeTableNode"),
    ("data", "ExecuteSqlNode"),
    ("data", "OpenGraphOverlayNode"),
    ("data", "CreateGraphOverlayNode"),
    ("data", "CreateLocalDatabaseNode"),
    ("data", "GraphAnalyticsNode"),
    ("data", "CypherQueryNode"),
    ("data", "DropGraphOverlayNode"),
    ("data", "ListGraphOverlaysNode"),
    ("data", "GraphNeighborsNode"),
    ("data", "OntologyActionRequestNode"),
    ("data", "OntologyActionInputNode"),
    ("data", "RemoteOntologyActionRequestNode"),
    ("data", "QueryOntologyObjectsNode"),
    ("data", "QueryRemoteOntologyChildrenNode"),
    ("data", "QueryRemoteOntologyObjectsNode"),
    ("data", "GraphPathsNode"),
    ("data", "GraphSampleNode"),
    ("data", "GraphSchemaNode"),
    ("data", "GraphSearchNode"),
    ("data", "GraphSqlQueryNode"),
    ("data", "GraphSubgraphNode"),
    ("data", "UpsertGraphEdgeNode"),
    ("data", "UpsertGraphNodeNode"),
    ("data", "AddColumnLocalDatabaseNode"),
    ("data", "CountLocalDatabaseNode"),
    ("data", "DeleteLocalDatabaseNode"),
    ("data", "DropColumnLocalDatabaseNode"),
    ("data", "DropIndexNode"),
    ("data", "DropTableLocalDatabaseNode"),
    ("data", "FilterLocalDatabaseNode"),
    ("data", "FlushLocalDatabaseNode"),
    ("data", "FTSLocalDatabaseNode"),
    ("data", "HybridSearchLocalDatabaseNode"),
    ("data", "IndexLocalDatabaseNode"),
    ("data", "InsertLocalDatabaseNode"),
    ("data", "BatchInsertLocalDatabaseNode"),
    ("data", "BatchInsertCSVLocalDatabaseNode"),
    ("data", "ListLocalDatabaseNode"),
    ("data", "ListIndicesNode"),
    ("data", "MakeColumnOptionalLocalDatabaseNode"),
    ("data", "OpenRemoteDatabaseNode"),
    ("data", "OptimizeLocalDatabaseNode"),
    ("data", "PurgeLocalDatabaseNode"),
    ("data", "GetSchemaLocalDatabaseNode"),
    ("data", "UpsertLocalDatabaseNode"),
    ("data", "BatchUpsertLocalDatabaseNode"),
    ("data", "VectorSearchLocalDatabaseNode"),
    ("data", "CopyWorksheetNode"),
    ("data", "GetRowByIndexNode"),
    ("data", "GetSheetNamesNode"),
    ("data", "InsertColumnNode"),
    ("data", "InsertRowNode"),
    ("data", "RowLoopNode"),
    ("data", "NewWorksheetNode"),
    ("data", "ReadCellNode"),
    ("data", "RemoveColumnNode"),
    ("data", "RemoveRowNode"),
    ("data", "ExtractExcelTablesNode"),
    ("data", "ExtractExcelTablesAINode"),
    ("data", "WriteCellNode"),
    ("data", "WriteCellHtmlNode"),
    ("data", "ListGitHubBranchesNode"),
    ("data", "GetGitHubBranchNode"),
    ("data", "CreateGitHubBranchNode"),
    ("data", "DeleteGitHubBranchNode"),
    ("data", "CloneGitHubRepoNode"),
    ("data", "ListGitHubCommitsNode"),
    ("data", "GetGitHubCommitNode"),
    ("data", "CompareGitHubCommitsNode"),
    ("data", "CreateGitHubIssueNode"),
    ("data", "GetGitHubFileContentsNode"),
    ("data", "CreateOrUpdateGitHubFileNode"),
    ("data", "DeleteGitHubFileNode"),
    ("data", "DownloadGitHubFileNode"),
    ("data", "GetGitHubRepoNode"),
    ("data", "GetGitHubUserNode"),
    ("data", "GetGitHubIssueNode"),
    ("data", "UpdateGitHubIssueNode"),
    ("data", "AddGitHubIssueCommentNode"),
    ("data", "ListGitHubIssueCommentsNode"),
    ("data", "ListGitHubIssuesNode"),
    ("data", "ListGitHubPullRequestsNode"),
    ("data", "ListGitHubReposNode"),
    ("data", "GitHubPatProviderNode"),
    ("data", "GitHubOAuthProviderNode"),
    ("data", "GitHubAppProviderNode"),
    ("data", "GetGitHubPullRequestNode"),
    ("data", "CreateGitHubPullRequestNode"),
    ("data", "UpdateGitHubPullRequestNode"),
    ("data", "MergeGitHubPullRequestNode"),
    ("data", "ListGitHubPullRequestFilesNode"),
    ("data", "ListGitHubPullRequestReviewsNode"),
    ("data", "CreateGitHubPullRequestReviewNode"),
    ("data", "ListGitHubReleasesNode"),
    ("data", "GetLatestGitHubReleaseNode"),
    ("data", "GetGitHubReleaseByTagNode"),
    ("data", "CreateGitHubReleaseNode"),
    ("data", "ListGitHubReleaseAssetsNode"),
    ("data", "UploadGitHubReleaseAssetNode"),
    ("data", "DownloadGitHubReleaseAssetNode"),
    ("data", "SearchGitHubCodeNode"),
    ("data", "SearchGitHubIssuesNode"),
    ("data", "SearchGitHubReposNode"),
    ("data", "ListWorkflowsNode"),
    ("data", "TriggerWorkflowNode"),
    ("data", "ListWorkflowRunsNode"),
    ("data", "GetWorkflowRunNode"),
    ("data", "CancelWorkflowRunNode"),
    ("data", "RerunWorkflowNode"),
    ("data", "GetLatestWorkflowRunNode"),
    ("data", "ListGoogleCalendarsNode"),
    ("data", "ListGoogleCalendarEventsNode"),
    ("data", "GetGoogleCalendarEventNode"),
    ("data", "CreateGoogleCalendarEventNode"),
    ("data", "UpdateGoogleCalendarEventNode"),
    ("data", "DeleteGoogleCalendarEventNode"),
    ("data", "QuickAddGoogleCalendarEventNode"),
    ("data", "QueryFreeBusyNode"),
    ("data", "CreateGoogleDocNode"),
    ("data", "GetGoogleDocNode"),
    ("data", "GetGoogleDocTextNode"),
    ("data", "InsertGoogleDocTextNode"),
    ("data", "DeleteGoogleDocTextNode"),
    ("data", "ReplaceGoogleDocTextNode"),
    ("data", "ExportGoogleDocNode"),
    ("data", "CreateGoogleDriveFolderNode"),
    ("data", "DeleteGoogleDriveFileNode"),
    ("data", "CopyGoogleDriveFileNode"),
    ("data", "MoveGoogleDriveFileNode"),
    ("data", "SearchGoogleDriveNode"),
    ("data", "GetGoogleDriveFileMetadataNode"),
    ("data", "UploadGoogleDriveFileNode"),
    ("data", "DownloadGoogleDriveFileNode"),
    ("data", "GetGoogleFormNode"),
    ("data", "ListGoogleFormResponsesNode"),
    ("data", "GetGoogleFormResponseNode"),
    ("data", "CreateGoogleFormNode"),
    ("data", "UpdateGoogleFormInfoNode"),
    ("data", "SendGmailNode"),
    ("data", "CreateGmailDraftNode"),
    ("data", "ListGmailLabelsNode"),
    ("data", "ListGoogleDriveFilesNode"),
    ("data", "CreateGoogleMeetNode"),
    ("data", "CreateInstantMeetNode"),
    ("data", "GetGoogleMeetDetailsNode"),
    ("data", "AddMeetToEventNode"),
    ("data", "GoogleProviderNode"),
    ("data", "ReadGoogleDriveFileNode"),
    ("data", "CreateGoogleSpreadsheetNode"),
    ("data", "GetGoogleSpreadsheetNode"),
    ("data", "ReadGoogleSheetsRangeNode"),
    ("data", "WriteGoogleSheetsRangeNode"),
    ("data", "AppendGoogleSheetsRowsNode"),
    ("data", "ClearGoogleSheetsRangeNode"),
    ("data", "AddGoogleSheetNode"),
    ("data", "DeleteGoogleSheetNode"),
    ("data", "CreateGoogleSlidesNode"),
    ("data", "GetGoogleSlidesNode"),
    ("data", "AddGoogleSlideNode"),
    ("data", "DeleteGoogleSlideNode"),
    ("data", "AddTextToSlideNode"),
    ("data", "ExportGoogleSlidesNode"),
    ("data", "SearchYouTubeVideosNode"),
    ("data", "GetYouTubeVideoNode"),
    ("data", "ListMyYouTubeVideosNode"),
    ("data", "GetYouTubeChannelNode"),
    ("data", "ListYouTubePlaylistsNode"),
    ("data", "GetYouTubePlaylistItemsNode"),
    ("data", "AddToYouTubePlaylistNode"),
    ("data", "RemoveFromYouTubePlaylistNode"),
    ("data", "LinkedInOAuthProviderNode"),
    ("data", "ShareTextPostNode"),
    ("data", "ShareArticleNode"),
    ("data", "ListCalendarsNode"),
    ("data", "CreateCalendarNode"),
    ("data", "ListEventsNode"),
    ("data", "CreateEventNode"),
    ("data", "DeleteEventNode"),
    ("data", "FindMeetingTimesNode"),
    ("data", "GetScheduleNode"),
    ("data", "UpdateEventNode"),
    ("data", "GetCopilotInteractionsNode"),
    ("data", "ListMeetingInsightsNode"),
    ("data", "GetMeetingInsightNode"),
    ("data", "CopilotChatNode"),
    ("data", "CopilotSemanticSearchNode"),
    ("data", "SubscribeCopilotNotificationsNode"),
    ("data", "GetUserCopilotSettingsNode"),
    ("data", "FilterCopilotInteractionsByTypeNode"),
    ("data", "ListExcelWorksheetsNode"),
    ("data", "ReadExcelRangeNode"),
    ("data", "WriteExcelRangeNode"),
    ("data", "GetExcelUsedRangeNode"),
    ("data", "GetExcelTableNode"),
    ("data", "AddExcelTableRowNode"),
    ("data", "MicrosoftGraphRequestNode"),
    ("data", "ListOneDriveItemsNode"),
    ("data", "GetOneDriveItemNode"),
    ("data", "DownloadOneDriveFileNode"),
    ("data", "UploadOneDriveFileNode"),
    ("data", "CreateOneDriveFolderNode"),
    ("data", "DeleteOneDriveItemNode"),
    ("data", "MoveOneDriveItemNode"),
    ("data", "CopyOneDriveItemNode"),
    ("data", "SearchOneDriveNode"),
    ("data", "ListNotebooksNode"),
    ("data", "CreateNotebookNode"),
    ("data", "ListSectionsNode"),
    ("data", "CreateSectionNode"),
    ("data", "ListPagesNode"),
    ("data", "CreatePageNode"),
    ("data", "GetPageContentNode"),
    ("data", "DeletePageNode"),
    ("data", "ListOutlookMailFoldersNode"),
    ("data", "ListOutlookMessagesNode"),
    ("data", "GetOutlookMessageNode"),
    ("data", "GetOutlookMessageAttachmentsNode"),
    ("data", "OutlookAttachmentFieldsNode"),
    ("data", "SendOutlookMessageNode"),
    ("data", "ListOutlookCalendarEventsNode"),
    ("data", "ListOutlookContactsNode"),
    ("data", "CreateOutlookCalendarEventNode"),
    ("data", "UpdateOutlookCalendarEventNode"),
    ("data", "DeleteOutlookCalendarEventNode"),
    ("data", "GetOutlookCalendarEventNode"),
    ("data", "RsvpOutlookCalendarEventNode"),
    ("data", "ForwardOutlookCalendarEventNode"),
    ("data", "ListMyPlansNode"),
    ("data", "GetPlanNode"),
    ("data", "ListPlanTasksNode"),
    ("data", "ListPlanBucketsNode"),
    ("data", "CreatePlannerTaskNode"),
    ("data", "UpdatePlannerTaskNode"),
    ("data", "CreateBucketNode"),
    ("data", "ListMyTasksNode"),
    ("data", "MicrosoftGraphTokenProviderNode"),
    ("data", "MicrosoftGraphOAuthProviderNode"),
    ("data", "SearchSharePointSitesNode"),
    ("data", "GetSharePointSiteNode"),
    ("data", "ListSharePointDrivesNode"),
    ("data", "ListSharePointDriveItemsNode"),
    ("data", "DownloadSharePointFileNode"),
    ("data", "GetSharePointDriveItemNode"),
    ("data", "UploadSharePointFileNode"),
    ("data", "CreateSharePointFolderNode"),
    ("data", "DeleteSharePointDriveItemNode"),
    ("data", "MoveSharePointDriveItemNode"),
    ("data", "CopySharePointDriveItemNode"),
    ("data", "SearchSharePointDriveItemsNode"),
    ("data", "ListSharePointListsNode"),
    ("data", "GetSharePointListItemsNode"),
    ("data", "GetSharePointListItemNode"),
    ("data", "CreateSharePointListItemNode"),
    ("data", "UpdateSharePointListItemFieldsNode"),
    ("data", "DeleteSharePointListItemNode"),
    ("data", "ListJoinedTeamsNode"),
    ("data", "ListTeamChannelsNode"),
    ("data", "SendChannelMessageNode"),
    ("data", "GetChannelMessagesNode"),
    ("data", "CreateTeamNode"),
    ("data", "CreateChannelNode"),
    ("data", "ListTaskListsNode"),
    ("data", "CreateTaskListNode"),
    ("data", "ListTasksNode"),
    ("data", "CreateTaskNode"),
    ("data", "UpdateTaskNode"),
    ("data", "CompleteTaskNode"),
    ("data", "DeleteTaskNode"),
    ("data", "ListNotionBlockChildrenNode"),
    ("data", "AppendNotionBlockChildrenNode"),
    ("data", "UpdateNotionBlockNode"),
    ("data", "DeleteNotionBlockNode"),
    ("data", "CreateNotionPageNode"),
    ("data", "GetNotionDataSourceNode"),
    ("data", "QueryNotionDataSourceNode"),
    ("data", "CreateNotionDataSourceNode"),
    ("data", "UpdateNotionDataSourceNode"),
    ("data", "UploadNotionFileNode"),
    ("data", "DownloadNotionFileNode"),
    ("data", "GetNotionDatabaseNode"),
    ("data", "GetNotionPageNode"),
    ("data", "ListNotionDatabasesNode"),
    ("data", "NotionApiKeyProviderNode"),
    ("data", "NotionOAuthProviderNode"),
    ("data", "QueryNotionDatabaseNode"),
    ("data", "SearchNotionNode"),
    ("data", "UpdateNotionPageNode"),
    ("data", "PathBufToPathNode"),
    ("data", "ReadToBytesNode"),
    ("data", "ReadToStringNode"),
    ("data", "WriteBytesNode"),
    ("data", "WriteStringNode"),
    ("data", "PathFromCacheDirNode"),
    ("data", "PathFromStorageDirNode"),
    ("data", "PathFromUploadDirNode"),
    ("data", "PathFromUserDirNode"),
    ("data", "VirtualDirNode"),
    ("data", "ChildNode"),
    ("data", "ExtensionNode"),
    ("data", "FilenameNode"),
    ("data", "SetFilenameNode"),
    ("data", "FromRawPathNode"),
    ("data", "ParentNode"),
    ("data", "RawPathNode"),
    ("data", "ReplaceSegmentNode"),
    ("data", "SetExtensionNode"),
    ("data", "CopyNode"),
    ("data", "DeleteNode"),
    ("data", "PathExistsNode"),
    ("data", "GetNode"),
    ("data", "GetRangeNode"),
    ("data", "HashFileNode"),
    ("data", "HeadNode"),
    ("data", "ListFoldersNode"),
    ("data", "ListPathsNode"),
    ("data", "ListWithOffsetNode"),
    ("data", "PutNode"),
    ("data", "RenameNode"),
    ("data", "SignUrlNode"),
    ("data", "SignUrlsNode"),
    ("data", "WriteManifestNode"),
    ("data", "GetChangesNode"),
    ("data", "AwsProviderNode"),
    ("data", "AzureProviderNode"),
    ("data", "CloudflareProviderNode"),
    ("data", "GcpProviderNode"),
    ("data", "BatchInsertTdmsLocalDatabaseNode"),
    ("data", "TdmsMetadataNode"),
    ("data", "CallRemoteEventNode"),
    ("data", "CallRemoteApiNode"),
    ("data", "CallRemoteChatNode"),
    ("data", "ChatEventNode"),
    ("data", "ExtractActionContextField"),
    ("data", "ExtractInputValue"),
    ("data", "GenericEventNode"),
    ("data", "SimpleEventNode"),
    ("data", "WidgetActionEvent"),
    ("data", "AttachmentFromPathNode"),
    ("data", "AttachmentFromUrlNode"),
    ("data", "AttachmentToUrlNode"),
    ("data", "PushAttachmentNode"),
    ("data", "PushAttachmentsNode"),
    ("data", "PushChunkNode"),
    ("data", "PushGlobalSessionNode"),
    ("data", "PushLocalSessionNode"),
    ("data", "PushReasoningNode"),
    ("data", "PushResponseNode"),
    ("data", "PushStatNode"),
    ("data", "PushStatsNode"),
    ("data", "PushStepNode"),
    ("data", "PushTextToStepNode"),
    ("data", "PushWidgetNode"),
    ("data", "PushWidgetsNode"),
    ("data", "RemoveStepNode"),
    ("data", "ReturnGenericResultNode"),
    ("data", "FormInteraction"),
    ("data", "MultipleChoiceInteraction"),
    ("data", "SingleChoiceInteraction"),
    ("geo", "CellAreaNode"),
    ("geo", "CellToBoundaryNode"),
    ("geo", "CellToChildrenNode"),
    ("geo", "CellToLatLngNode"),
    ("geo", "CellToParentNode"),
    ("geo", "CellsToMultiPolygonNode"),
    ("geo", "CompactCellsNode"),
    ("geo", "EdgeLengthNode"),
    ("geo", "GridDiskNode"),
    ("geo", "GridDistanceNode"),
    ("geo", "GridPathNode"),
    ("geo", "LatLngToCellNode"),
    ("geo", "GetMapImageNode"),
    ("geo", "OsrmMatchTraceNode"),
    ("geo", "OsrmNearestNode"),
    ("geo", "PlanRouteNode"),
    ("geo", "OsrmTableNode"),
    ("geo", "OsrmTileNode"),
    ("geo", "OsrmTripNode"),
    ("geo", "ReverseGeocodeNode"),
    ("geo", "SearchLocationNode"),
    ("llm", "AddDataFusionNode"),
    ("llm", "AgentFromModelNode"),
    ("llm", "InvokeAgentNode"),
    ("llm", "LazyRegisterFunctionToolsNode"),
    ("llm", "RegisterMcpToolsNode"),
    ("llm", "RegisterRemoteMcpToolsNode"),
    ("llm", "RegisterThinkingToolNode"),
    ("llm", "RegisterFunctionToolsNode"),
    ("llm", "SetAgentSystemPromptNode"),
    ("llm", "SimpleAgentNode"),
    ("llm", "StreamInvokeAgentNode"),
    ("llm", "BuildMemoryContextNode"),
    ("llm", "CompressMemoryNode"),
    ("llm", "CreateMemoryConfigNode"),
    ("llm", "OptimizeMemoryNode"),
    ("llm", "RegisterMemoryNode"),
    ("llm", "SearchMemoryNode"),
    ("llm", "StoreMemoryNode"),
    ("llm", "KgExtractNode"),
    ("llm", "KgRetrieveNode"),
    ("llm", "KgSummarizeNode"),
    ("llm", "KgTraverseToolNode"),
    ("llm", "CopilotLocalClientBuilderNode"),
    ("llm", "CopilotServerClientBuilderNode"),
    ("llm", "CopilotLocalClientStartNode"),
    ("llm", "CopilotServerClientStartNode"),
    ("llm", "CopilotClientStopNode"),
    ("llm", "CopilotInfiniteSessionNode"),
    ("llm", "CopilotSystemMessageNode"),
    ("llm", "CopilotCustomAgentNode"),
    ("llm", "CopilotProviderConfigNode"),
    ("llm", "CopilotSendAndWaitNode"),
    ("llm", "CopilotSendStreamingNode"),
    ("llm", "CopilotAbortNode"),
    ("llm", "CopilotMcpLocalServerNode"),
    ("llm", "CopilotMcpHttpServerNode"),
    ("llm", "CopilotSessionBuilderNode"),
    ("llm", "CopilotCreateSessionNode"),
    ("llm", "CopilotDestroySessionNode"),
    ("llm", "CopilotToolConfigNode"),
    ("llm", "CopilotToolListNode"),
    ("llm", "CopilotGetVersionNode"),
    ("llm", "CopilotGetModelsNode"),
    ("llm", "CopilotGetAuthStatusNode"),
    ("llm", "CopilotClientStatusNode"),
    ("llm", "LoadModelNode"),
    ("llm", "EmbedImageNode"),
    ("llm", "ChunkText"),
    ("llm", "ChunkTextChar"),
    ("llm", "EmbedDocumentNode"),
    ("llm", "EmbedQueryNode"),
    ("llm", "AddModelHeadersNode"),
    ("llm", "LLMBranchNode"),
    ("llm", "FindLLMNode"),
    ("llm", "InvokeLLM"),
    ("llm", "InvokeLLMSimpleNode"),
    ("llm", "InvokeLLMWithToolsNode"),
    ("llm", "LLMExtractNode"),
    ("llm", "LLMExtractHistoryNode"),
    ("llm", "SummarizeNode"),
    ("llm", "ClearHistoryNode"),
    ("llm", "ExtractAttachments"),
    ("llm", "FromMessagesNode"),
    ("llm", "HistoryFromStringNode"),
    ("llm", "GetSystemPromptNode"),
    ("llm", "MakeHistoryNode"),
    ("llm", "PopHistoryMessageNode"),
    ("llm", "PushHistoryMessageNode"),
    ("llm", "SetHistoryFrequencyPenaltyNode"),
    ("llm", "SetHistoryMaxTokensNode"),
    ("llm", "SetHistoryNNode"),
    ("llm", "SetHistoryPresencePenaltyNode"),
    ("llm", "SetHistoryResponseFormatNode"),
    ("llm", "SetHistorySeedNode"),
    ("llm", "SetHistoryStopWordsNode"),
    ("llm", "SetHistoryStreamNode"),
    ("llm", "SetSystemPromptMessageNode"),
    ("llm", "SetHistoryTemperatureNode"),
    ("llm", "SetHistoryThinkingNode"),
    ("llm", "SetHistoryTopPNode"),
    ("llm", "SetHistoryUserNode"),
    ("llm", "ExtractContentNode"),
    ("llm", "MakeHistoryMessageNode"),
    ("llm", "PushContentNode"),
    ("llm", "SetModelHintNode"),
    ("llm", "MakePreferencesNode"),
    ("llm", "SetWeightNode"),
    ("llm", "BuildAnthropicNode"),
    ("llm", "BuildAtlasCloudNode"),
    ("llm", "BuildBedrockNode"),
    ("llm", "BuildCohereNode"),
    ("llm", "BuildDeepseekNode"),
    ("llm", "BuildGaladrielNode"),
    ("llm", "BuildGeminiNode"),
    ("llm", "BuildGroqNode"),
    ("llm", "BuildHuggingfaceNode"),
    ("llm", "BuildHyperbolicNode"),
    ("llm", "BuildLMStudioNode"),
    ("llm", "BuildMiniMaxNode"),
    ("llm", "BuildMiraNode"),
    ("llm", "BuildMistralNode"),
    ("llm", "BuildMoonshotNode"),
    ("llm", "BuildMozillaNode"),
    ("llm", "BuildOllamaNode"),
    ("llm", "BuildOpenAiNode"),
    ("llm", "BuildOpenRouterNode"),
    ("llm", "BuildPerplexityNode"),
    ("llm", "BuildTogetherNode"),
    ("llm", "BuildVertexNode"),
    ("llm", "BuildVoyageAINode"),
    ("llm", "BuildXAINode"),
    ("llm", "ChunkFromStringNode"),
    ("llm", "LastContentNode"),
    ("llm", "LastMessageNode"),
    ("llm", "MakeResponseNode"),
    ("llm", "PushChunkNode"),
    ("llm", "ResponseFromStringNode"),
    ("llm", "GetTokenNode"),
    ("llm", "GetContentNode"),
    ("llm", "GetRoleNode"),
    ("media", "MakeOpenAiCompatibleTextToSpeechOptionsNode"),
    ("media", "MakeXaiTextToSpeechOptionsNode"),
    ("media", "MakeGoogleTextToSpeechOptionsNode"),
    ("media", "MakeHuggingFaceTextToSpeechOptionsNode"),
    ("media", "MakeMistralTextToSpeechOptionsNode"),
    ("media", "MakeOpenAiCompatibleSpeechToTextOptionsNode"),
    ("media", "MakeXaiSpeechToTextOptionsNode"),
    ("media", "MakeGoogleSpeechToTextOptionsNode"),
    ("media", "TextToSpeechNode"),
    ("media", "LocalTextToSpeechNode"),
    ("media", "SpeechToTextNode"),
    ("media", "LocalSpeechToTextNode"),
    ("media", "MakeOpenAiSoraVideoOptionsNode"),
    ("media", "MakeVertexVeoVideoOptionsNode"),
    ("media", "MakeRunwayVideoOptionsNode"),
    ("media", "MakeFalVideoOptionsNode"),
    ("media", "MakeReplicateVideoOptionsNode"),
    ("media", "BuildRunwayVideoProviderNode"),
    ("media", "BuildFalVideoProviderNode"),
    ("media", "BuildReplicateVideoProviderNode"),
    ("media", "GenerateVideoNode"),
    ("media", "BitFromStringNode"),
    ("media", "IsBitOfTypeNode"),
    ("media", "SwitchOnBitNode"),
    ("media", "DocxAddHeaderFooterNode"),
    ("media", "DocxAddHyperlinkNode"),
    ("media", "DocxAddImageNode"),
    ("media", "DocxAddPageBreakNode"),
    ("media", "DocxAddParagraphNode"),
    ("media", "DocxAddTableNode"),
    ("media", "DocxAddTocNode"),
    ("media", "DocxCreateNode"),
    ("media", "DocxExtractTextNode"),
    ("media", "DocxListPlaceholdersNode"),
    ("media", "DocxMergeNode"),
    ("media", "DocxSetMetadataNode"),
    ("media", "DocxGetMetadataNode"),
    ("media", "DocxRemoveParagraphNode"),
    ("media", "DocxReplaceImageNode"),
    ("media", "DocxReplaceTableRowNode"),
    ("media", "DocxReplaceTextNode"),
    ("media", "PdfAddImageStampNode"),
    ("media", "PdfAddPageNumbersNode"),
    ("media", "PdfAddWatermarkNode"),
    ("media", "PdfCompressNode"),
    ("media", "PdfCreateFromMarkdownNode"),
    ("media", "PdfDecryptNode"),
    ("media", "PdfEncryptNode"),
    ("media", "PdfExtractPagesNode"),
    ("media", "PdfExtractTextNode"),
    ("media", "PdfFillFormNode"),
    ("media", "PdfListFormFieldsNode"),
    ("media", "PdfMergeNode"),
    ("media", "PdfSetMetadataNode"),
    ("media", "PdfGetMetadataNode"),
    ("media", "PdfPageCountNode"),
    ("media", "PdfReplaceImageNode"),
    ("media", "PdfReplaceTextNode"),
    ("media", "PdfRotatePagesNode"),
    ("media", "PdfSplitNode"),
    ("media", "PptxAddChartNode"),
    ("media", "PptxAddImageToSlideNode"),
    ("media", "PptxAddNotesNode"),
    ("media", "PptxAddShapeNode"),
    ("media", "PptxAddSlideNode"),
    ("media", "PptxAddTableToSlideNode"),
    ("media", "PptxAddTextBoxNode"),
    ("media", "PptxCreateNode"),
    ("media", "PptxDeleteSlideNode"),
    ("media", "PptxDuplicateSlideNode"),
    ("media", "PptxExtractTextNode"),
    ("media", "PptxListPlaceholdersNode"),
    ("media", "PptxMergeNode"),
    ("media", "PptxSetMetadataNode"),
    ("media", "PptxGetMetadataNode"),
    ("media", "PptxReorderSlidesNode"),
    ("media", "PptxReplaceImageNode"),
    ("media", "PptxReplaceTableDataNode"),
    ("media", "PptxReplaceTextNode"),
    ("media", "PptxSlideCountNode"),
    ("media", "MakeOpenAiImageOptionsNode"),
    ("media", "MakeGoogleImagenOptionsNode"),
    ("media", "MakeAwsBedrockImageOptionsNode"),
    ("media", "MakeXaiImageOptionsNode"),
    ("media", "MakeTogetherImageOptionsNode"),
    ("media", "MakeHuggingFaceImageOptionsNode"),
    ("media", "MakeOpenRouterImageOptionsNode"),
    ("media", "GenerateImageNode"),
    ("media", "DrawBoxesNode"),
    ("media", "MakeBoxNode"),
    ("media", "ReadBarcodesNode"),
    ("media", "ReadImagePathNode"),
    ("media", "ReadImageFromUrlNode"),
    ("media", "WriteQrCodeNode"),
    ("media", "WriteImageDataUrlNode"),
    ("media", "WriteImageNode"),
    ("media", "ImageDimsNode"),
    ("media", "ImageOverlayNode"),
    ("media", "TextOverlayNode"),
    ("media", "PdfPageToImageNode"),
    ("media", "PdfToImagesNode"),
    ("media", "ContrastImageNode"),
    ("media", "ConvertImageNode"),
    ("media", "CropImageNode"),
    ("media", "ResizeImageNode"),
    ("media", "AddSubtitleTrackNode"),
    ("media", "AnalyzeAudioNode"),
    ("media", "AudioToWavNode"),
    ("media", "BitstreamConvertNode"),
    ("media", "BurnSubtitlesNode"),
    ("media", "CheckRemuxCompatibilityNode"),
    ("media", "ConcatMediaNode"),
    ("media", "ContactSheetNode"),
    ("media", "ConvertImageFormatNode"),
    ("media", "DetectVideoContainerNode"),
    ("media", "DetectSilenceNode"),
    ("media", "EncodeAv1Node"),
    ("media", "ExtractSubtitleTrackNode"),
    ("media", "ExtractThumbnailNode"),
    ("media", "ExtractTrackNode"),
    ("media", "NormalizePacketTimestampsNode"),
    ("media", "PackageHlsVodNode"),
    ("media", "ParseSubtitlesNode"),
    ("media", "PickCodecBackendNode"),
    ("media", "ProbeCodecBackendsNode"),
    ("media", "ProbeMediaInfoNode"),
    ("media", "ProbePlatformCodecNode"),
    ("media", "RemuxVideoNode"),
    ("media", "ShiftSubtitleFileNode"),
    ("media", "TranscodeVideoNode"),
    ("media", "TransformAudioNode"),
    ("media", "TransformImageNode"),
    ("media", "TransformVideoNode"),
    ("media", "TrimOnKeyframesNode"),
    ("media", "WriteSubtitlesNode"),
    ("ml", "LoadMLModelNode"),
    ("ml", "LoadMLModelBinaryNode"),
    ("ml", "MLPredictNode"),
    ("ml", "SaveMLModelNode"),
    ("ml", "SaveMLModelBinaryNode"),
    ("ml", "FitAdaBoostNode"),
    ("ml", "FitDecisionTreeNode"),
    ("ml", "FitKnnClassifierNode"),
    ("ml", "FitLogisticRegressionNode"),
    ("ml", "FitMultinomialNaiveBayesNode"),
    ("ml", "FitNaiveBayesNode"),
    ("ml", "FitOneClassSVMNode"),
    ("ml", "FitRandomForestNode"),
    ("ml", "FitSVMMultiClassNode"),
    ("ml", "FitDbscanNode"),
    ("ml", "FitGaussianMixtureNode"),
    ("ml", "FitKMeansNode"),
    ("ml", "SampleDatasetNode"),
    ("ml", "ShuffleDatasetNode"),
    ("ml", "SplitDatasetNode"),
    ("ml", "StratifiedSplitNode"),
    ("ml", "AccuracyNode"),
    ("ml", "ConfusionMatrixNode"),
    ("ml", "RegressionMetricsNode"),
    ("ml", "RocAucNode"),
    ("ml", "SilhouetteScoreNode"),
    ("ml", "GetKMeansCentroidsNode"),
    ("ml", "GetLinearCoefficientsNode"),
    ("ml", "GetFeatureImportanceNode"),
    ("ml", "GetModelInfoNode"),
    ("ml", "FitOrdinalAdjacentCategoryNode"),
    ("ml", "FitOrdinalContinuationRatioNode"),
    ("ml", "FitOrdinalFrankHallNode"),
    ("ml", "FitOrdinalLogisticNode"),
    ("ml", "OrdinalMetricsNode"),
    ("ml", "FitOrdinalNeuralNode"),
    ("ml", "FitOrdinalRidgeNode"),
    ("ml", "MLApplyTransformNode"),
    ("ml", "FitFeatureScalerNode"),
    ("ml", "FitTfIdfVectorizerNode"),
    ("ml", "FitPcaNode"),
    ("ml", "TsneNode"),
    ("ml", "FitElasticNetNode"),
    ("ml", "FitGlmNode"),
    ("ml", "FitKnnRegressorNode"),
    ("ml", "FitLinearRegressionNode"),
    ("ml", "FitSVMRegressionNode"),
    ("ml", "AutoClassifierNode"),
    ("ml", "AutoOrdinalNode"),
    ("ml", "GridSearchNode"),
    ("ml", "KFoldGeneratorNode"),
    ("ml", "OrdinalGridSearchNode"),
    ("onnx", "LoadAudioNode"),
    ("onnx", "VoiceActivityDetectionNode"),
    ("onnx", "ResampleAudioNode"),
    ("onnx", "TrimAudioNode"),
    ("onnx", "AudioToMelSpectrogramNode"),
    ("onnx", "BatchImageInferenceNode"),
    ("onnx", "ImageClassificationNode"),
    ("onnx", "DepthEstimationNode"),
    ("onnx", "DepthToPointCloudNode"),
    ("onnx", "DepthColorizeNode"),
    ("onnx", "ObjectDetectionNode"),
    ("onnx", "FaceDetectionNode"),
    ("onnx", "FaceEmbeddingNode"),
    ("onnx", "CompareFacesNode"),
    ("onnx", "CropFacesNode"),
    ("onnx", "LoadFaceAnalyzerNode"),
    ("onnx", "UnloadFaceAnalyzerNode"),
    ("onnx", "AnalyzeFacesNode"),
    ("onnx", "FeatureExtractionNode"),
    ("onnx", "FeatureSimilarityNode"),
    ("onnx", "GlinerNode"),
    ("onnx", "LoadOnnxNode"),
    ("onnx", "NerNode"),
    ("onnx", "TextDetectionNode"),
    ("onnx", "TextRecognitionNode"),
    ("onnx", "CropTextRegionsNode"),
    ("onnx", "PoseEstimationNode"),
    ("onnx", "ExtractKeypointNode"),
    ("onnx", "SemanticSegmentationNode"),
    ("onnx", "TeachableMachineNode"),
    ("onnx", "PredictionClassOrLabelNode"),
    ("onnx", "PredictionScoreNode"),
    ("onnx", "ModelInfoNode"),
    ("onnx", "UnloadOnnxNode"),
    ("onnx", "SessionInfoNode"),
    ("processing", "AiKeywordExtractionNode"),
    ("processing", "ExtractDocumentNode"),
    ("processing", "ExtractDocumentAiNode"),
    ("processing", "ExtractDocumentsNode"),
    ("processing", "ExtractDocumentsAiNode"),
    ("processing", "PagesToMarkdownNode"),
    ("processing", "SummarizeDocumentNode"),
    ("processing", "ExtractContentSectionsNode"),
    ("processing", "RakeExtractionNode"),
    ("processing", "YakeExtractionNode"),
    ("processing", "PiiDetectionOptionsNode"),
    ("processing", "PiiMaskAiNode"),
    ("processing", "PiiMaskRegexNode"),
    ("std", "BeginRendering"),
    ("std", "CreateComponent"),
    ("std", "CreateSurface"),
    ("std", "DataUpdate"),
    ("std", "DeleteSurface"),
    ("std", "GetWidgetElement"),
    ("std", "InstantiateWidget"),
    ("std", "PushToContainer"),
    ("std", "RemoveFromContainer"),
    ("std", "RequestElements"),
    ("std", "SetSurfaceCustomCss"),
    ("std", "SetWidgetText"),
    ("std", "ShowScreen"),
    ("std", "SurfaceUpdate"),
    ("std", "UpsertElement"),
    ("std", "WidgetQuery"),
    ("std", "WidgetUpdateInputs"),
    ("std", "ChartDataAgent"),
    ("std", "ClearChildren"),
    ("std", "ClearInput"),
    ("std", "CloneElement"),
    ("std", "CloseDialog"),
    ("std", "CreateElement"),
    ("std", "GetButtonDisabled"),
    ("std", "GetButtonLabel"),
    ("std", "GetButtonLoading"),
    ("std", "GetChildAtIndex"),
    ("std", "GetCurrentRoute"),
    ("std", "GetElement"),
    ("std", "GetElementText"),
    ("std", "GetElementValue"),
    ("std", "GetFileInputFiles"),
    ("std", "GetIframeSrc"),
    ("std", "GetInputPlaceholder"),
    ("std", "GetQueryParams"),
    ("std", "GetRouteParams"),
    ("std", "GetSelectValue"),
    ("std", "GetTooltipContent"),
    ("std", "NavigateTo"),
    ("std", "OpenDialog"),
    ("std", "PushChild"),
    ("std", "PushChildAtIndex"),
    ("std", "PushCsvToChart"),
    ("std", "QueryChildren"),
    ("std", "QueryElementsById"),
    ("std", "QueryElementsByType"),
    ("std", "QueryParent"),
    ("std", "RemoveChildAtIndex"),
    ("std", "RemoveElement"),
    ("std", "SetBadgeContent"),
    ("std", "SetButtonLabel"),
    ("std", "SetChartLayout"),
    ("std", "SetChartStyle"),
    ("std", "SetDiffContent"),
    ("std", "SetElementAction"),
    ("std", "SetElementDisabled"),
    ("std", "SetElementLoading"),
    ("std", "SetElementStyle"),
    ("std", "SetElementText"),
    ("std", "SetElementValue"),
    ("std", "SetElementVisibility"),
    ("std", "SetIcon"),
    ("std", "SetIframeSrc"),
    ("std", "SetIframeSrcdoc"),
    ("std", "SetInputPlaceholder"),
    ("std", "SetMarkdownContent"),
    ("std", "SetMediaSource"),
    ("std", "SetNivoConfig"),
    ("std", "SetProgress"),
    ("std", "SetQueryParam"),
    ("std", "SetSelectOptions"),
    ("std", "SetSelectValue"),
    ("std", "SetSliderValue"),
    ("std", "SetTextFieldError"),
    ("std", "SetTooltipContent"),
    ("std", "UpdateCalendar"),
    ("std", "UpdateGantt"),
    ("std", "UpdateGeoMap"),
    ("std", "UpdateGraph"),
    ("std", "UpdateHotspot"),
    ("std", "UpdateLabeler"),
    ("std", "UpdateModel3d"),
    ("std", "UpdateOverlay"),
    ("std", "UpdateScene3d"),
    ("std", "UpdateSprite"),
    ("std", "UpdateTable"),
    ("std", "UpdateToggle"),
    ("std", "UrlDecode"),
    ("std", "UrlEncode"),
    ("std", "WriteCsvToTable"),
    ("std", "GetGlobalState"),
    ("std", "GetPageState"),
    ("std", "SetGlobalState"),
    ("std", "SetPageState"),
    ("std", "BranchNode"),
    ("std", "CallFunctionNode"),
    ("std", "CallReferenceNode"),
    ("std", "DelayNode"),
    ("std", "DoNNode"),
    ("std", "DoOnceNode"),
    ("std", "FlipFlopNode"),
    ("std", "LoopNode"),
    ("std", "BatchLoopNode"),
    ("std", "ForEachWithBreakNode"),
    ("std", "GateNode"),
    ("std", "GatherExecutionNode"),
    ("std", "ParallelExecutionNode"),
    ("std", "ParLoopNode"),
    ("std", "ParBatchLoopNode"),
    ("std", "RerouteNode"),
    ("std", "SequenceNode"),
    ("std", "SwitchNode"),
    ("std", "TimeoutNode"),
    ("std", "WhileLoopNode"),
    ("std", "FakeStreetName"),
    ("std", "FakeStreetAddress"),
    ("std", "FakeCityName"),
    ("std", "FakeStateName"),
    ("std", "FakeCountryName"),
    ("std", "FakeCountryCode"),
    ("std", "FakePostCode"),
    ("std", "FakeLatitude"),
    ("std", "FakeLongitude"),
    ("std", "FakeCompanyName"),
    ("std", "FakeBuzzword"),
    ("std", "FakeCatchPhrase"),
    ("std", "FakeIndustry"),
    ("std", "FakeProfession"),
    ("std", "FakeEmail"),
    ("std", "FakeUsername"),
    ("std", "FakePassword"),
    ("std", "FakeIPv4"),
    ("std", "FakeIPv6"),
    ("std", "FakeUserAgent"),
    ("std", "FakeDomainSuffix"),
    ("std", "FakeWord"),
    ("std", "FakeWords"),
    ("std", "FakeSentence"),
    ("std", "FakeSentences"),
    ("std", "FakeParagraph"),
    ("std", "FakeParagraphs"),
    ("std", "FakeFirstName"),
    ("std", "FakeLastName"),
    ("std", "FakeFullName"),
    ("std", "FakeTitle"),
    ("std", "FakeInteger"),
    ("std", "FakeFloat"),
    ("std", "FakeBoolean"),
    ("std", "FakeDigit"),
    ("std", "FakePhoneNumber"),
    ("std", "FakeCellNumber"),
    ("std", "ErrorNode"),
    ("std", "InfoNode"),
    ("std", "ProgressNode"),
    ("std", "ProgressDoneNode"),
    ("std", "WarningNode"),
    ("std", "NotifyProjectUserNode"),
    ("std", "NotifyUserNode"),
    ("std", "BreakStructNode"),
    ("std", "CastToSchemaNode"),
    ("std", "CastToStructNode"),
    ("std", "MakeStructNode"),
    ("std", "MakeStructFromSchemaNode"),
    ("std", "MergeStructNode"),
    ("std", "PickStructNode"),
    ("std", "GetStructFieldNode"),
    ("std", "ListStructFields"),
    ("std", "HasStructFieldNode"),
    ("std", "RemoveStructFieldNode"),
    ("std", "SetStructFieldNode"),
    ("std", "FlowAssertNode"),
    ("std", "GenerateEncryptionKeyNode"),
    ("std", "AesEncryptBytesNode"),
    ("std", "AesDecryptBytesNode"),
    ("std", "AesEncryptValueNode"),
    ("std", "AesDecryptValueNode"),
    ("std", "XChaCha20EncryptBytesNode"),
    ("std", "XChaCha20DecryptBytesNode"),
    ("std", "XChaCha20EncryptValueNode"),
    ("std", "XChaCha20DecryptValueNode"),
    ("std", "CuidNode"),
    ("std", "GetExecutionEnvironmentNode"),
    ("std", "IsLocalEnvironmentNode"),
    ("std", "IsServerEnvironmentNode"),
    ("std", "IsMobileEnvironmentNode"),
    ("std", "GetRunIdNode"),
    ("std", "GetAppIdNode"),
    ("std", "GetUserIdNode"),
    ("std", "GetExecutionModeNode"),
    ("std", "UuidV4Node"),
    ("std", "UuidV7Node"),
    ("std", "RandomStringNode"),
    ("std", "RandomChoiceNode"),
    ("std", "ZipArrayNode"),
    ("std", "SumFieldArrayNode"),
    ("std", "BatchPushArrayNode"),
    ("std", "BatchRemoveArrayNode"),
    ("std", "BatchSetArrayNode"),
    ("std", "UniqueArrayNode"),
    ("std", "GroupArrayByNode"),
    ("std", "PluckArrayNode"),
    ("std", "MinByArrayNode"),
    ("std", "MaxByArrayNode"),
    ("std", "ClearArrayNode"),
    ("std", "ClearArrayRefNode"),
    ("std", "ConstructArrayNode"),
    ("std", "ExtendArrayNode"),
    ("std", "ExtendArrayRefNode"),
    ("std", "FilterArrayByNode"),
    ("std", "FilterArrayFieldNode"),
    ("std", "FilterArrayFieldsNode"),
    ("std", "FindItemInArrayNode"),
    ("std", "GetArrayElementNode"),
    ("std", "ArrayIncludesNode"),
    ("std", "JoinArraysNode"),
    ("std", "ArrayLengthNode"),
    ("std", "MakeArrayNode"),
    ("std", "PopArrayNode"),
    ("std", "PopArrayRefNode"),
    ("std", "PushArrayNode"),
    ("std", "PushArrayRefNode"),
    ("std", "RemoveArrayIndexNode"),
    ("std", "RemoveIndexArrayRefNode"),
    ("std", "SetIndexArrayNode"),
    ("std", "SetIndexArrayRefNode"),
    ("std", "ChunkArrayNode"),
    ("std", "FlattenArrayNode"),
    ("std", "ShuffleArrayNode"),
    ("std", "SortArrayNode"),
    ("std", "ReverseArrayNode"),
    ("std", "SliceArrayNode"),
    ("std", "BoolAllNode"),
    ("std", "BoolAnyNode"),
    ("std", "BoolAnd"),
    ("std", "BoolToIntNode"),
    ("std", "BoolToStringNode"),
    ("std", "IntToBoolNode"),
    ("std", "BoolEqual"),
    ("std", "BoolNandNode"),
    ("std", "BoolNorNode"),
    ("std", "BoolImpliesNode"),
    ("std", "BoolNot"),
    ("std", "BoolOr"),
    ("std", "RandomBoolNode"),
    ("std", "BoolToggleNode"),
    ("std", "BoolUnequalNode"),
    ("std", "BoolXor"),
    ("std", "BytesGzipCompressNode"),
    ("std", "BytesGzipDecompressNode"),
    ("std", "BytesDetectTypeNode"),
    ("std", "BytesLengthNode"),
    ("std", "BytesConcatNode"),
    ("std", "BytesSliceNode"),
    ("std", "BytesEqualNode"),
    ("std", "BytesStartsWithNode"),
    ("std", "BytesToTextNode"),
    ("std", "TextToBytesNode"),
    ("std", "BufferedCsvReaderNode"),
    ("std", "DateBusinessDaysBetweenNode"),
    ("std", "DateAddBusinessDaysNode"),
    ("std", "DateBeforeNode"),
    ("std", "DateAfterNode"),
    ("std", "DateSameNode"),
    ("std", "DateBetweenNode"),
    ("std", "DateTimeDiffNode"),
    ("std", "DateTimeDurationNode"),
    ("std", "DateTimeFormatNode"),
    ("std", "DateHumanizeNode"),
    ("std", "DateFromPartsNode"),
    ("std", "DateCalendarInfoNode"),
    ("std", "DateMinNode"),
    ("std", "DateMaxNode"),
    ("std", "DateMinOfNode"),
    ("std", "DateMaxOfNode"),
    ("std", "DateClampNode"),
    ("std", "DateTimeNowNode"),
    ("std", "DateTimeParseNode"),
    ("std", "DateToTimezoneNode"),
    ("std", "DateTimeToDateNode"),
    ("std", "DateTimeToTimeNode"),
    ("std", "DateStartOfNode"),
    ("std", "DateEndOfNode"),
    ("std", "DateShiftNode"),
    ("std", "DateToUnixNode"),
    ("std", "DateFromUnixNode"),
    ("std", "Base64DecodeNode"),
    ("std", "Base64DecodeBytesNode"),
    ("std", "Base64EncodeNode"),
    ("std", "Base64EncodeBytesNode"),
    ("std", "HexDecodeNode"),
    ("std", "HexDecodeBytesNode"),
    ("std", "HexEncodeNode"),
    ("std", "HexEncodeBytesNode"),
    ("std", "HtmlDecodeNode"),
    ("std", "HtmlEncodeNode"),
    ("std", "UrlDecodeNode"),
    ("std", "UrlEncodeNode"),
    ("std", "AbsFloatNode"),
    ("std", "AddFloatNode"),
    ("std", "FloatSumNode"),
    ("std", "FloatAverageNode"),
    ("std", "FloatMinOfNode"),
    ("std", "FloatMaxOfNode"),
    ("std", "FloatMedianNode"),
    ("std", "FloatVarianceNode"),
    ("std", "FloatStdDevNode"),
    ("std", "FloatPercentileNode"),
    ("std", "FloatToDegreesNode"),
    ("std", "FloatToRadiansNode"),
    ("std", "FloatRecipNode"),
    ("std", "FloatHypotNode"),
    ("std", "FloatCopySignNode"),
    ("std", "FloatMulAddNode"),
    ("std", "FloatLerpNode"),
    ("std", "CeilFloatNode"),
    ("std", "FloatIsNanNode"),
    ("std", "FloatIsFiniteNode"),
    ("std", "FloatIsInfiniteNode"),
    ("std", "ClampFloatNode"),
    ("std", "FloatConstantNode"),
    ("std", "DivideFloatNode"),
    ("std", "EqualFloatNode"),
    ("std", "FloorFloatNode"),
    ("std", "GreaterThanFloatNode"),
    ("std", "GreaterThanOrEqualFloatNode"),
    ("std", "FloatLnNode"),
    ("std", "FloatLog10Node"),
    ("std", "FloatLog2Node"),
    ("std", "FloatLogNode"),
    ("std", "FloatExpNode"),
    ("std", "FloatExp2Node"),
    ("std", "FloatSqrtNode"),
    ("std", "LessThanFloatNode"),
    ("std", "LessThanOrEqualFloatNode"),
    ("std", "MaxFloatNode"),
    ("std", "MinFloatNode"),
    ("std", "FloatModuloNode"),
    ("std", "MultiplyFloatNode"),
    ("std", "FloatTruncNode"),
    ("std", "FloatFractNode"),
    ("std", "FloatSignumNode"),
    ("std", "PowerFloatNode"),
    ("std", "RandomFloatInRangeNode"),
    ("std", "RootFloatNode"),
    ("std", "RoundFloatNode"),
    ("std", "SubtractFloatNode"),
    ("std", "FloatToIntNode"),
    ("std", "FloatSinNode"),
    ("std", "FloatCosNode"),
    ("std", "FloatTanNode"),
    ("std", "FloatAsinNode"),
    ("std", "FloatAcosNode"),
    ("std", "FloatAtanNode"),
    ("std", "FloatAtan2Node"),
    ("std", "FloatSinhNode"),
    ("std", "FloatCoshNode"),
    ("std", "FloatTanhNode"),
    ("std", "UnequalFloatNode"),
    ("std", "FormatNumberNode"),
    ("std", "FormatBytesNode"),
    ("std", "FormatOrdinalNode"),
    ("std", "MapRangeNode"),
    ("std", "PercentChangeNode"),
    ("std", "FormatDurationNode"),
    ("std", "RoundToMultipleNode"),
    ("std", "AHashNode"),
    ("std", "Blake3Node"),
    ("std", "Md5Node"),
    ("std", "Sha256Node"),
    ("std", "Sha512Node"),
    ("std", "AbsoluteIntegerNode"),
    ("std", "AddIntegerNode"),
    ("std", "IntSumNode"),
    ("std", "IntProductNode"),
    ("std", "IntAverageNode"),
    ("std", "IntMinOfNode"),
    ("std", "IntMaxOfNode"),
    ("std", "IntCountOnesNode"),
    ("std", "IntLeadingZerosNode"),
    ("std", "IntTrailingZerosNode"),
    ("std", "IntBitAndNode"),
    ("std", "IntBitOrNode"),
    ("std", "IntBitXorNode"),
    ("std", "IntShiftLeftNode"),
    ("std", "IntShiftRightNode"),
    ("std", "IntBitNotNode"),
    ("std", "ClampIntegerNode"),
    ("std", "IntToFloatNode"),
    ("std", "IntToRadixNode"),
    ("std", "IntFromRadixNode"),
    ("std", "IntDivNode"),
    ("std", "IntDivEuclidNode"),
    ("std", "IntRemEuclidNode"),
    ("std", "DivideIntegerNode"),
    ("std", "EqualIntegerNode"),
    ("std", "IntGcdNode"),
    ("std", "IntLcmNode"),
    ("std", "GreaterThanIntegerNode"),
    ("std", "GreaterThanOrEqualIntegerNode"),
    ("std", "IntLimitsNode"),
    ("std", "LessThanIntegerNode"),
    ("std", "LessThanOrEqualIntegerNode"),
    ("std", "MaxIntegerNode"),
    ("std", "MinIntegerNode"),
    ("std", "ModuloIntegerNode"),
    ("std", "MultiplyIntegerNode"),
    ("std", "PowerIntegerNode"),
    ("std", "RandomIntegerInRangeNode"),
    ("std", "RootIntegerNode"),
    ("std", "IntCheckedOpNode"),
    ("std", "IntSaturatingOpNode"),
    ("std", "IntWrappingOpNode"),
    ("std", "IntNegateNode"),
    ("std", "IntSignumNode"),
    ("std", "IntIsEvenNode"),
    ("std", "IntIsOddNode"),
    ("std", "IntIsPositiveNode"),
    ("std", "IntIsNegativeNode"),
    ("std", "IntIncrementNode"),
    ("std", "IntDecrementNode"),
    ("std", "SubtractIntegerNode"),
    ("std", "UnequalIntegerNode"),
    ("std", "SchemaFromExample"),
    ("std", "ParseWithSchema"),
    ("std", "RepairParseNode"),
    ("std", "ClearMapNode"),
    ("std", "ClearMapRefNode"),
    ("std", "GetMapNode"),
    ("std", "HasKeyMapNode"),
    ("std", "KeysMapNode"),
    ("std", "MakeMapNode"),
    ("std", "RemoveMapNode"),
    ("std", "RemoveMapRefNode"),
    ("std", "SetMapNode"),
    ("std", "SetMapRefNode"),
    ("std", "SizeMapNode"),
    ("std", "ValuesMapNode"),
    ("std", "EvalNode"),
    ("std", "HTMLToMarkdownNode"),
    ("std", "MarkdownToHtmlNode"),
    ("std", "PlateJsonToHtmlNode"),
    ("std", "PlateJsonToMarkdownNode"),
    ("std", "ClearSetNode"),
    ("std", "ClearSetRefNode"),
    ("std", "DifferenceSetNode"),
    ("std", "DiscardSetNode"),
    ("std", "DiscardSetRefNode"),
    ("std", "ArrayToSetNode"),
    ("std", "SetHasNode"),
    ("std", "InsertSetNode"),
    ("std", "InsertSetRefNode"),
    ("std", "SetIsEmptyNode"),
    ("std", "SetIsSubsetNode"),
    ("std", "SetIsSuperSetNode"),
    ("std", "MakeSetNode"),
    ("std", "IsMutualSetNode"),
    ("std", "PopSetNode"),
    ("std", "SetGetSizeNode"),
    ("std", "SetToArrayNode"),
    ("std", "UnionSetNode"),
    ("std", "StringCapitalizeNode"),
    ("std", "StringTitleCaseNode"),
    ("std", "StringSnakeCaseNode"),
    ("std", "StringKebabCaseNode"),
    ("std", "StringCamelCaseNode"),
    ("std", "StringConvertCaseNode"),
    ("std", "StringDetectCaseNode"),
    ("std", "StringIsEmptyNode"),
    ("std", "StringToCharsNode"),
    ("std", "StringCharAtNode"),
    ("std", "StringReverseNode"),
    ("std", "StringRepeatNode"),
    ("std", "StringLinesNode"),
    ("std", "StringConcatNode"),
    ("std", "StringContainsNode"),
    ("std", "StringEllipsisNode"),
    ("std", "StringEndsWithNode"),
    ("std", "EqualStringNode"),
    ("std", "StringEscapeNode"),
    ("std", "FormatStringNode"),
    ("std", "StringJoinNode"),
    ("std", "StringLengthNode"),
    ("std", "StringPadStartNode"),
    ("std", "StringPadEndNode"),
    ("std", "StringNormalizeWhitespaceNode"),
    ("std", "StringToIntNode"),
    ("std", "StringToFloatNode"),
    ("std", "StringToBoolNode"),
    ("std", "StringRegexMatchNode"),
    ("std", "StringRegexFindAllNode"),
    ("std", "StringRegexCapturesNode"),
    ("std", "StringReplaceNode"),
    ("std", "StringIndexOfNode"),
    ("std", "StringLastIndexOfNode"),
    ("std", "StringCountMatchesNode"),
    ("std", "StringContainsAnyNode"),
    ("std", "StringStartsWithAnyNode"),
    ("std", "StringSlugifyNode"),
    ("std", "StringWordCountNode"),
    ("std", "StringMaskNode"),
    ("std", "StringExtractNode"),
    ("std", "StringSplitNode"),
    ("std", "StringSplitOnceNode"),
    ("std", "StringSplitWhitespaceNode"),
    ("std", "StringStartsWithNode"),
    ("std", "StringSubstringNode"),
    ("std", "StringTruncateNode"),
    ("std", "StringSplitAtNode"),
    ("std", "TemplateStringNode"),
    ("std", "StringToLowerNode"),
    ("std", "StringToUpperNode"),
    ("std", "StringTrimNode"),
    ("std", "StringTrimStartNode"),
    ("std", "StringTrimEndNode"),
    ("std", "StringTrimMatchesNode"),
    ("std", "StringStripPrefixNode"),
    ("std", "StringStripSuffixNode"),
    ("std", "UnEqualStringNode"),
    ("std", "StringUnescapeNode"),
    ("std", "ParseUtf8LossyNode"),
    ("std", "StringIsNumericNode"),
    ("std", "StringIsAlphanumericNode"),
    ("std", "StringIsAsciiNode"),
    ("std", "StringIsEmailNode"),
    ("std", "StringIsUrlNode"),
    ("std", "StringIsUuidNode"),
    ("std", "StringIsIpNode"),
    ("std", "StringIsJsonNode"),
    ("std", "DamerauLevenshteinDistanceNode"),
    ("std", "HammingDistanceNode"),
    ("std", "JaroDistanceNode"),
    ("std", "JaroWinklerDistanceNode"),
    ("std", "LevenshteinDistanceNode"),
    ("std", "OptimalStringAlignmentDistanceNode"),
    ("std", "SorensenDiceCoefficientNode"),
    ("std", "FallbackNode"),
    ("std", "FromBytesNode"),
    ("std", "FromStringNode"),
    ("std", "TypeOfNode"),
    ("std", "IsEmptyValueNode"),
    ("std", "SelectNode"),
    ("std", "ToBytesNode"),
    ("std", "ToStringNode"),
    ("std", "TryTransformNode"),
    ("std", "GetCurrentUserInfoNode"),
    ("std", "GetExecutingUserNode"),
    ("std", "HasAttributeNode"),
    ("std", "HasPermissionNode"),
    ("std", "IsTechnicalUserNode"),
    ("std", "CheckUserHasRoleNode"),
    ("std", "CheckUserPermissionNode"),
    ("std", "GetCurrentUserNode"),
    ("std", "GetEffectiveUserPermissionsNode"),
    ("std", "GetProjectUserNode"),
    ("std", "GetUserAttributeNode"),
    ("std", "GetUserAttributesNode"),
    ("std", "GetUserRolesNode"),
    ("std", "ListProjectUsersNode"),
    ("std", "ListUsersWithAttributeNode"),
    ("std", "ListUsersWithRoleNode"),
    ("std", "ResolveUserNode"),
    ("std", "SearchUsersNode"),
    ("std", "FloatVectorAdditionNode"),
    ("std", "FloatVectorCosineSimilarityNode"),
    ("std", "FloatVectorCrossProductNode"),
    ("std", "FloatVectorDotProductNode"),
    ("std", "FloatVectorMultiplicationNode"),
    ("std", "FloatVectorNormalizeNode"),
    ("std", "FloatVectorSubtractionNode"),
    ("std", "GetVariable"),
    ("std", "SetVariable"),
    ("web", "CreateThreadNode"),
    ("web", "GetChannelInfoNode"),
    ("web", "SetChannelTopicNode"),
    ("web", "TypingIndicatorNode"),
    ("web", "SendDMNode"),
    ("web", "SendDMByIdNode"),
    ("web", "SendAndWaitNode"),
    ("web", "WaitForMessageNode"),
    ("web", "SendButtonsNode"),
    ("web", "SendSelectMenuNode"),
    ("web", "DisableComponentsNode"),
    ("web", "SendFileNode"),
    ("web", "SendImageNode"),
    ("web", "SendMultipleFilesNode"),
    ("web", "EditMessageWithFileNode"),
    ("web", "SendMessageNode"),
    ("web", "EditMessageNode"),
    ("web", "DeleteMessageNode"),
    ("web", "PinMessageNode"),
    ("web", "UnpinMessageNode"),
    ("web", "SendPollNode"),
    ("web", "GetPollResultsNode"),
    ("web", "EndPollNode"),
    ("web", "AddReactionNode"),
    ("web", "RemoveReactionNode"),
    ("web", "ClearReactionsNode"),
    ("web", "ToDiscordSessionNode"),
    ("web", "ToDiscordUserNode"),
    ("web", "ImapConnectNode"),
    ("web", "SmtpConnectNode"),
    ("web", "ImapListCalendarEventsNode"),
    ("web", "ImapListCalendarsNode"),
    ("web", "ImapSubscribeCalendarNode"),
    ("web", "ImapGetCalendarEventNode"),
    ("web", "ImapCreateCalendarEventNode"),
    ("web", "ImapDeleteCalendarEventNode"),
    ("web", "ImapInboxNode"),
    ("web", "ImapListInboxesNode"),
    ("web", "ImapCreateMailboxNode"),
    ("web", "ListMailsNode"),
    ("web", "FetchMailNode"),
    ("web", "EmailHeadersNode"),
    ("web", "EmailContentNode"),
    ("web", "EmailAttachmentsNode"),
    ("web", "MailAddressFieldsNode"),
    ("web", "AttachmentFieldsNode"),
    ("web", "ToMailReferenceNode"),
    ("web", "ImapCopyMailNode"),
    ("web", "ImapDeleteMailNode"),
    ("web", "ImapCreateDraftNode"),
    ("web", "ImapMarkSeenNode"),
    ("web", "ImapMoveMailNode"),
    ("web", "SmtpSendMailNode"),
    ("web", "GetMeNode"),
    ("web", "LogOutNode"),
    ("web", "CloseNode"),
    ("web", "GetBusinessConnectionNode"),
    ("web", "SendBusinessMessageNode"),
    ("web", "ForwardBusinessMessageNode"),
    ("web", "EditBusinessMessageTextNode"),
    ("web", "StopBusinessPollNode"),
    ("web", "DeleteBusinessMessageNode"),
    ("web", "SendBusinessPhotoNode"),
    ("web", "SendBusinessDocumentNode"),
    ("web", "GetChatInfoNode"),
    ("web", "GetChatMemberCountNode"),
    ("web", "SendChatActionNode"),
    ("web", "UnpinAllMessagesNode"),
    ("web", "LeaveChatNode"),
    ("web", "SetChatPermissionsNode"),
    ("web", "SetChatPhotoNode"),
    ("web", "DeleteChatPhotoNode"),
    ("web", "SetChatTitleNode"),
    ("web", "SetChatDescriptionNode"),
    ("web", "GetChatNode"),
    ("web", "SetChatStickerSetNode"),
    ("web", "DeleteChatStickerSetNode"),
    ("web", "BanChatSenderChatNode"),
    ("web", "UnbanChatSenderChatNode"),
    ("web", "SetMyCommandsNode"),
    ("web", "DeleteMyCommandsNode"),
    ("web", "GetMyCommandsNode"),
    ("web", "SetMyNameNode"),
    ("web", "GetMyNameNode"),
    ("web", "SetMyDescriptionNode"),
    ("web", "GetMyDescriptionNode"),
    ("web", "SetMyShortDescriptionNode"),
    ("web", "GetMyShortDescriptionNode"),
    ("web", "SetChatMenuButtonNode"),
    ("web", "GetChatMenuButtonNode"),
    ("web", "SetMyDefaultAdminRightsNode"),
    ("web", "GetMyDefaultAdminRightsNode"),
    ("web", "GetFileNode"),
    ("web", "GetUserProfilePhotosNode"),
    ("web", "DeleteMessagesNode"),
    ("web", "ForwardMessagesNode"),
    ("web", "CopyMessagesNode"),
    ("web", "CreateForumTopicNode"),
    ("web", "EditForumTopicNode"),
    ("web", "CloseForumTopicNode"),
    ("web", "ReopenForumTopicNode"),
    ("web", "DeleteForumTopicNode"),
    ("web", "UnpinAllForumTopicMessagesNode"),
    ("web", "EditGeneralForumTopicNode"),
    ("web", "CloseGeneralForumTopicNode"),
    ("web", "ReopenGeneralForumTopicNode"),
    ("web", "HideGeneralForumTopicNode"),
    ("web", "UnhideGeneralForumTopicNode"),
    ("web", "GetForumTopicIconStickersNode"),
    ("web", "UnpinAllGeneralForumTopicMessagesNode"),
    ("web", "SendGameNode"),
    ("web", "SetGameScoreNode"),
    ("web", "GetGameHighScoresNode"),
    ("web", "SetGameScoreInlineNode"),
    ("web", "GetAvailableGiftsNode"),
    ("web", "SendGiftNode"),
    ("web", "SendGiftChatNode"),
    ("web", "GiftPremiumSubscriptionNode"),
    ("web", "ConvertGiftToStarsNode"),
    ("web", "UpgradeGiftNode"),
    ("web", "TransferGiftNode"),
    ("web", "AnswerInlineQueryNode"),
    ("web", "AnswerWebAppQueryNode"),
    ("web", "WaitForReplyNode"),
    ("web", "WaitForCallbackNode"),
    ("web", "AnswerCallbackQueryNode"),
    ("web", "ConfirmationDialogNode"),
    ("web", "SendDiceNode"),
    ("web", "SendLocationNode"),
    ("web", "SendVenueNode"),
    ("web", "SendContactNode"),
    ("web", "ExportChatInviteLinkNode"),
    ("web", "CreateChatInviteLinkNode"),
    ("web", "EditChatInviteLinkNode"),
    ("web", "RevokeChatInviteLinkNode"),
    ("web", "CreateChatSubscriptionInviteLinkNode"),
    ("web", "EditChatSubscriptionInviteLinkNode"),
    ("web", "SendPhotoNode"),
    ("web", "SendDocumentNode"),
    ("web", "SendVideoNode"),
    ("web", "SendAudioNode"),
    ("web", "SendVoiceNode"),
    ("web", "SendStickerNode"),
    ("web", "SendAnimationNode"),
    ("web", "SendPhotoFromFileNode"),
    ("web", "SendDocumentFromFileNode"),
    ("web", "SendVideoFromFileNode"),
    ("web", "SendAudioFromFileNode"),
    ("web", "SendVoiceFromFileNode"),
    ("web", "SendAnimationFromFileNode"),
    ("web", "GetChatMemberNode"),
    ("web", "GetChatAdministratorsNode"),
    ("web", "BanChatMemberNode"),
    ("web", "UnbanChatMemberNode"),
    ("web", "RestrictChatMemberNode"),
    ("web", "PromoteChatMemberNode"),
    ("web", "SetChatAdministratorCustomTitleNode"),
    ("web", "ApproveChatJoinRequestNode"),
    ("web", "DeclineChatJoinRequestNode"),
    ("web", "ForwardMessageNode"),
    ("web", "ReplyToMessageNode"),
    ("web", "CopyMessageNode"),
    ("web", "EditMessageLiveLocationNode"),
    ("web", "StopMessageLiveLocationNode"),
    ("web", "SendMediaGroupNode"),
    ("web", "SendVideoNoteNode"),
    ("web", "SetMessageReactionNode"),
    ("web", "EditMessageMediaNode"),
    ("web", "SendInvoiceNode"),
    ("web", "CreateInvoiceLinkNode"),
    ("web", "AnswerShippingQueryNode"),
    ("web", "AnswerPreCheckoutQueryNode"),
    ("web", "GetStarTransactionsNode"),
    ("web", "RefundStarPaymentNode"),
    ("web", "SendPollWithRefNode"),
    ("web", "StopPollNode"),
    ("web", "SendQuizNode"),
    ("web", "ToTelegramSessionNode"),
    ("web", "GetStickerSetNode"),
    ("web", "GetCustomEmojiStickersNode"),
    ("web", "SetStickerSetThumbnailNode"),
    ("web", "SetStickerEmojiListNode"),
    ("web", "SetStickerKeywordsNode"),
    ("web", "SetStickerMaskPositionNode"),
    ("web", "DeleteStickerFromSetNode"),
    ("web", "SetStickerSetTitleNode"),
    ("web", "DeleteStickerSetNode"),
    ("web", "UploadStickerFileNode"),
    ("web", "CreateNewStickerSetNode"),
    ("web", "AddStickerToSetNode"),
    ("web", "SetStickerPositionInSetNode"),
    ("web", "ReplaceStickerInSetNode"),
    ("web", "SetCustomEmojiStickerSetThumbnailNode"),
    ("web", "PostStoryNode"),
    ("web", "EditStoryNode"),
    ("web", "DeleteStoryNode"),
    ("web", "ToTelegramUserNode"),
    ("web", "GetTelegramUserIdNode"),
    ("web", "GetUserChatBoostsNode"),
    ("web", "SetUserEmojiStatusNode"),
    ("web", "CreateMcpServerConfigNode"),
    ("web", "RegisterMcpFunctionsNode"),
    ("web", "RegisterMcpAuthNode"),
    ("web", "RegisterMcpResourceNode"),
    ("web", "RegisterMcpPromptNode"),
    ("web", "McpServerNode"),
    ("web", "McpEchoLogic"),
    ("web", "McpRefLogic"),
    ("web", "NoopLogic"),
    ("web", "CreateRestServerConfigNode"),
    ("web", "RegisterRestFunctionNode"),
    ("web", "RegisterRestFilesNode"),
    ("web", "RegisterRestOpenApiNode"),
    ("web", "CreateApiKeyAuthNode"),
    ("web", "CreateBearerTokenAuthNode"),
    ("web", "CreateBasicAuthNode"),
    ("web", "CreateHmacSha256AuthNode"),
    ("web", "CreateOidcDiscoveryAuthNode"),
    ("web", "CreateOAuthJwksUrlAuthNode"),
    ("web", "CreateOAuthJwksFileAuthNode"),
    ("web", "RegisterRestAuthNode"),
    ("web", "RestServerNode"),
    ("web", "RestEchoLogic"),
    ("web", "RestQueryLogic"),
    ("web", "CreateCaCertificateNode"),
    ("web", "CreateCaSignedCertificateNode"),
    ("web", "CreateSelfSignedCertificateNode"),
    ("web", "HttpDownloadNode"),
    ("web", "HttpFetchNode"),
    ("web", "StreamingHttpFetchNode"),
    ("web", "GetHeaderNode"),
    ("web", "GetHeadersNode"),
    ("web", "GetMethodNode"),
    ("web", "GetUrlNode"),
    ("web", "MakeRequestNode"),
    ("web", "SetAcceptNode"),
    ("web", "SetBearerAuthNode"),
    ("web", "SetBytesBodyNode"),
    ("web", "SetContentTypeNode"),
    ("web", "SetFormBodyNode"),
    ("web", "SetHeaderNode"),
    ("web", "SetHeadersNode"),
    ("web", "SetMethodNode"),
    ("web", "SetStringBodyNode"),
    ("web", "SetStructBodyNode"),
    ("web", "SetUrlNode"),
    ("web", "GetStatusNode"),
    ("web", "IsSuccessNode"),
    ("web", "ToBytesNode"),
    ("web", "ToJsonNode"),
    ("web", "ToTextNode"),
    ("web", "GrabFrameNode"),
    ("web", "GrabRtspFrameNode"),
    ("web", "MqttBrokerNode"),
    ("web", "MqttConnectNode"),
    ("web", "MqttDisconnectNode"),
    ("web", "MqttPublishNode"),
    ("web", "MqttSubscribeNode"),
    ("web", "ExtractLinksNode"),
    ("web", "TcpCloseNode"),
    ("web", "TcpConnectNode"),
    ("web", "TcpListenNode"),
    ("web", "TcpSendNode"),
    ("web", "TcpServerNode"),
    ("web", "UdpBindNode"),
    ("web", "UdpCloseNode"),
    ("web", "UdpReceiveNode"),
    ("web", "UdpSendToNode"),
    ("web", "UdpServerNode"),
    ("web", "WebSocketCloseNode"),
    ("web", "WebSocketConnectNode"),
    ("web", "WebSocketSendNode"),
    ("web", "WebSocketServerNode"),
];
