//! API-key providers sourced from the DX Router catalog.
//!
//! These entries intentionally contain only identities. Router's catalog does
//! not publish a universally safe direct endpoint for every provider, so the
//! TUI must not silently send their credentials to OpenAI's endpoint.

/// Router API-key providers not already represented by the DX/Agent catalogs.
pub const PROVIDERS: &[&str] = &[
    "302ai",
    "360ai",
    "abacus",
    "abliteration",
    "alibaba-cn",
    "alibaba-coding-plan",
    "alibaba-coding-plan-cn",
    "alibaba-token-plan",
    "alibaba-token-plan-cn",
    "amazon-nova",
    "ambient",
    "anyapi",
    "api-serpent",
    "auriko",
    "azure-openai",
    "bailing",
    "bedrock-mantle",
    "berget",
    "black-forest-labs",
    "blueclaw",
    "clarifai",
    "claudinio",
    "cloudferro-sherlock",
    "cloudflare-ai-gateway",
    "cohere-chat",
    "cortecs",
    "crossmodel",
    "crusoe",
    "daoxe",
    "darkbloom",
    "datarobot",
    "digitalocean",
    "dinference",
    "empiriolabs",
    "empower",
    "evroc",
    "fal-ai",
    "fastrouter",
    "fenayai",
    "firecrawl",
    "frogbot",
    "getgoapi",
    "gitlab",
    "gitlawb-gmi",
    "glm-cn",
    "glmt",
    "gmi-cloud",
    "hcnsec",
    "helicone",
    "hpc-ai",
    "iflowcn",
    "inceptron",
    "inferx",
    "io-net",
    "jiekou",
    "jina-ai",
    "jina-reader",
    "kimi-coding-apikey",
    "kimi-for-coding",
    "kuae-cloud-coding-plan",
    "laozhang",
    "libertai",
    "lilac",
    "llm-gateway",
    "lucidquery",
    "maritalk",
    "meganova",
    "merge-gateway",
    "minimax-cn",
    "minimax-cn-coding-plan",
    "minimax-coding-plan",
    "mixlayer",
    "moark",
    "neon",
    "neosantara",
    "neuralwatt",
    "nomic",
    "oci",
    "opencode-go",
    "opencode-zen",
    "openvecta",
    "parallel-ai",
    "piapi",
    "pinstripes",
    "poe",
    "poolside",
    "privatemode",
    "qihang-ai",
    "recraft",
    "regolo",
    "replicate",
    "requesty",
    "routing-run",
    "runwayml",
    "sakana",
    "sap",
    "sarvam",
    "stability-ai",
    "stackit",
    "stepfun-ai-step-plan",
    "stepfun-step-plan",
    "subconscious",
    "submodel",
    "suno",
    "tencent-coding-plan",
    "tencent-tokenhub",
    "tencent-token-plan",
    "tensormesh",
    "thebai",
    "the-grid-ai",
    "tinfoil",
    "tinyfish",
    "topaz",
    "trustedrouter",
    "umans-ai-coding-plan",
    "unorouter",
    "vertex-partner",
    "vivgrid",
    "voyage-ai",
    "watsonx",
    "xiaomi-token-plan-ams",
    "xiaomi-token-plan-cn",
    "xiaomi-token-plan-sgp",
    "xpersona",
    "zeldoc",
    "zhipuai-coding-plan",
];

/// Produce a readable fallback label without duplicating Router's UI strings.
pub fn display_name(id: &str) -> String {
    id.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
