[package]
name = "dx-parser-js"
version = "1.0.0"
edition = "2021"
description = "JavaScript/TypeScript parser for Dx editor plugins"

[dependencies]
anyhow.workspace = true
oxc_allocator = "0.128.0"
oxc_ast = "0.128.0"
oxc_parser = "0.128.0"
oxc_transformer = "0.128.0"
oxc_codegen = { version = "0.128.0", default-features = false }
oxc_span = "0.128.0"
oxc_semantic = "0.128.0"
oxc_isolated_declarations = "0.128.0"
